### PR TITLE
SP5: Add Coxcomb and Radar Plots

### PR DESCRIPTION
**Pull request by bclehmann**
Mentioned (in passing) in https://github.com/ScottPlot/ScottPlot/issues/3457

I think I will add radar charts as well (hence this is a draft PR), as the `StarAxis` will be useful there. The `StarAxis` stuff should be refactored out of `Coxcomb`, so whether radar charts are added to this PR or not we should find a place for the StarAxis before merge.

```cs
        List<PieSlice> slices = new()
{
    new PieSlice() { Value = 5, Label = "Red", Fill = new FillStyle() { Hatch = new ScottPlot.Hatches.Striped(), Color = Colors.Red.WithOpacity(0.75) } },
    new PieSlice() { Value = 2, Label = "Orange", Fill = new FillStyle() { Hatch = new ScottPlot.Hatches.Square(), Color = Colors.Orange.WithOpacity(0.75), HatchColor = Colors.White.WithOpacity(0.75) } },
    new PieSlice() { Value = 8, Label = "Yellow", Fill = new FillStyle() { Hatch = new ScottPlot.Hatches.Dots(), Color = Colors.Gold.WithOpacity(0.75), HatchColor = Colors.White.WithOpacity(0.75) } },
    new PieSlice() { Value = 4, FillColor = Colors.Green.WithOpacity(0.5), Label = "Green" },
    new PieSlice() { Value = 8, FillColor = Colors.Blue.WithOpacity(0.5), Label = "Blue" },
};

        var cox = myPlot.Add.Coxcomb(slices);
        //cox.AxisType = ScottPlot.Primitives.StarAxis.Polygon;

        myPlot.ShowLegend();
```
image

This PR factors out a `PieBase` from `PieChart`, and both coxcomb and pie charts subclass from this base class. I also found a fun issue where `paint.Shader` wasn't always cleared, leading to legend labels being drawn in different colours if they were preceded by legend items which had hatching.

I did also wonder if a `StarAxis` enum was the right move, or if it should be a class satisfying some interface. It's likely that the two provided web styles (circular and polygonal) are all anyone would want, but the tick logic might warrant some more extensibility (especially if people want tick labels?).

### CODE REVIEW

**Comment by bclehmann** [comment]
I've since refactored the star axes out into their own classes and I've added spokes:
image

I think you can merge this now if you want, or you can leave it open for me to start on radar charts.

**Comment by swharden** [comment]
> I think you can merge this now if you want, or you can leave it open for me to start on radar charts

Thanks for your work on this so far! I'm happy to leave it open so you can keep going on radar charts in this same branch. I'll probably be focusing on #3186 and some other projects for the next few days, so take as long as you need in this branch and let me know when it's ready to merge in 👍 🚀

**Comment by bclehmann** [comment]
I added radar charts, but this is still a WIP, ideally we should be able to label the spokes.
image

**Comment by bclehmann** [comment]
I'm also assuming that the default axis for coxcombs should be circular, and the default for radars should be polygonal, but this is a matter of taste. They can be changed freely if the user wants.

**Comment by bclehmann** [comment]
I think radars are ready:
```cs
List<RadarSeries> radarSeries = new()
{
    new RadarSeries() { Values = new double[] { 1, 2, 3, 4, 5 }, Label = "Orange", Fill = new FillStyle() { Hatch = new ScottPlot.Hatches.Square(), Color = Colors.Orange.WithOpacity(0.75), HatchColor = Colors.White.WithOpacity(0.75) } },
    new RadarSeries() { Values = new double[] { 5, 4, 5, 2, 3 }, Label = "Yellow", Fill = new FillStyle() { Hatch = new ScottPlot.Hatches.Dots(), Color = Colors.Gold.WithOpacity(0.75), HatchColor = Colors.White.WithOpacity(0.75) } },
    new RadarSeries() { Values = new double[] { 2, 3, 2, 3, 2}, Label = "Red", Fill = new FillStyle() { Hatch = new ScottPlot.Hatches.Striped(), Color = Colors.Red.WithOpacity(0.75) } }
};

var radar = myPlot.Add.Radar(radarSeries);
radar.Labels = new string[] { "Thing 1", "Thing 2", "Thing 3", "Thing 4", "Thing 5" }.Select(s => new Label() { Text = s, Alignment = Alignment.MiddleCenter }).ToArray();
myPlot.ShowLegend();
```

image

**Comment by swharden** [comment]
Thanks @bclehmann, amazing work as always! 🚀🚀🚀

**Pull request merged**
