### PR TITLE
SP5: support custom background image for figure and data area

### PR DESCRIPTION
**Pull request by unsigned-ru**
This PR adds the styling/configuring of a data frame background image 
with the plot properties: 
- `DataBackgroundImage`
- `DataBackgroundScalingStyle` 
- `DataBackgroundImageColor`. When this image is set it renders said image on top of the data frame Background.

...and the added styling functions:
- `DataBackgroundImage(...)`
- `ColorDataBackgroundImage(...)`

This feature was requested in issue #3405 

Scaling styles are applied in the renderer and currently support:
- `None` - _Render background as is and clip if its size exceeds the DataFrame rect._
- `StretchToFill` - _Render background stretched to fill the entire DataFrame rect._
- `FillRetainAspect` - _Render the background uniformly scaled so that either its width or height fills the DataFrame rect._

Example:
```cs
Plot myPlot = new();
myPlot.Style.DarkMode();

double[] sin = Generate.Sin(51);
double[] cos = Generate.Cos(51);
myPlot.Add.Signal(sin);
myPlot.Add.Signal(cos);

//set color of background image (50% opacity)
myPlot.Style.ColorDataBackgroundImage(Colors.White.WithOpacity(0.5f));

//test 1
myPlot.Title("Test: No scaling.", 40);
const string bgImgPath = "haikhuu-logo-arrow-white.png";
myPlot.Style.DataBackgroundImage(bgImgPath, ImageScalingStyle.None);
myPlot.SavePng("background-test-no-scaling.png", 1351, 789);

//test 2
myPlot.Title("Test: Stretch to fill.", 40);
myPlot.Style.DataBackgroundImage(bgImgPath, ImageScalingStyle.StretchToFill);
myPlot.SavePng("background-test-stretch-to-fill.png", 1351, 789);

//test 3
myPlot.Title("Test: Fill retain aspect ratio.", 40);
myPlot.Style.DataBackgroundImage(bgImgPath, ImageScalingStyle.FillRetainAspect);
myPlot.SavePng("background-test-fill-retain-aspect-ratio.png", 1351, 789);
```

Results:
background-test-no-scaling
background-test-stretch-to-fill
background-test-fill-retain-aspect-ratio

Original image:
haikhuu-logo-arrow-white

### CODE REVIEW

**Comment by swharden** [comment]
This is fantastic @unsigned-ru, thank you so much! I'm going to make some modifications to refine this a bit, then merge it into the main branch, and these new features will make it into the next release 🚀

**Comment by swharden** [comment]
Following-up, I made some improvements but I'm not finished yet. I'll put this down for now but pick it up tomorrow and hopefully merge it in then. Thanks again for your work on this, it's looking great!

**Comment by unsigned-ru** [comment]
Thanks a lot for your time as well and the improvements on this! Cool project to work on!

**Comment by swharden** [comment]
Following-up again, I'm taking a bit of time working on this. I don't think it's ready to merge today, but I'll keep working on it today and tomorrow and hopefully we will get it there soon! I created a new background image demo which I help will make it easier to evaluate all the combinations of options

image

**Comment by swharden** [comment]
Wow this PR got huge! Thanks for kicking all this off @unsigned-ru, this is awesome. 🚀 

 I'm merging now, but if you take a look at the new demo app I made and have any recommendations for improvements I'm happy to refine this work in the future 👍

**Pull request merged**
