### PR TITLE
Axes: improve sharpness of axis lines, tick marks, and grid lines

### PR DESCRIPTION
**Pull request by bforlgreen**
Allow users to be able to disable antialiasing on grid lines and ticks, which to my mind creates a more pleasing graph as the aa lines look blurry. The defaults have been left as they were, so this is an "opt into" change.

Before
AntiAlliased

After (with the configuration code below)
Aliased

```
     WpfPlot1.Plot.Axes.Left.FrameLineStyle.AntiAlias = false;
     WpfPlot1.Plot.Axes.Top.FrameLineStyle.AntiAlias = false;
     WpfPlot1.Plot.Axes.Right.FrameLineStyle.AntiAlias = false;
     WpfPlot1.Plot.Axes.Bottom.FrameLineStyle.AntiAlias = false;

     WpfPlot1.Plot.Grid.XAxisStyle.MajorLineStyle.AntiAlias = false;
     WpfPlot1.Plot.Grid.YAxisStyle.MajorLineStyle.AntiAlias = false;

     WpfPlot1.Plot.Axes.Left.MajorTickStyle.IsAntialias = false;
     WpfPlot1.Plot.Axes.Left.MinorTickStyle.IsAntialias = false;

     WpfPlot1.Plot.Axes.Bottom.MajorTickStyle.IsAntialias = false;
     WpfPlot1.Plot.Axes.Bottom.MinorTickStyle.IsAntialias = false;
```

I highly recommend the ZoomIt app for being able to investigate these kinds of issues.
https://learn.microsoft.com/en-us/sysinternals/downloads/zoomit

### CODE REVIEW

**Comment by swharden** [comment]
Hi @bforlgreen, fantastic observation! Thanks so much for this PR!

I'm liking what I'm seeing so much, I'm considering disabling anti-aliasing by default. Axis frames, axis lines, and tick marks look best when they are "crisp". I'll take a closer look and merge this in a few minutes! 🚀

**Comment by swharden** [comment]
I'm noticing a few small artifacts when frame anti-aliasing is disabled... I'll fix those two in this PR before I merge

image

**Comment by swharden** [comment]
This looks _so_ much better! Also I'm loving ZoomIt - thanks for the tip! 🚀 

AntiAlias = false | AntiAlias = true
---|---
image|image

**Comment by bforlgreen** [comment]
Great!

Yes, my observations are that its nice to have AA disabled for anything that you know will be a straight line.

I've done this for my bar charts too.

However, it's not a silver bullet, as it really depends on what you're showing. For example, lots of bars in a chart when zoom out (where there isn't much space to render them) can look worse with AA disabled. So you kind of what it dynamic with some heuristic

**Pull request merged**
