### PR TITLE
CoordinateRange: refactor and improve tests

### PR DESCRIPTION
**Pull request by CoderPM2011**
I reorganized `CoordinateRange` and added new properties and methods.
If something is wrong, please tell me. 😉

### CODE REVIEW

**Comment by swharden** [comment]
Hey @CoderPM2011, thanks for this PR! Wow, `CoordinateRange` was pretty sloppy 🤪 You did a great job making it better!

There's nothing you did that's incorrect, but for good measure I'll review this file line-by-line (and add tests as I go) because I want to make sure this looks nice and stays working as expected moving forward.

The biggest potential issue is that it's not clear whether `CoordinateRange` supports inverted ranges. The constructor arguments suggest that the first value should be less than the second, but I don't think it's enforced, and things like `Span` assume this is the case or a negative value could be returned (but maybe that's the desired behavior?). It's questions like this I'll think about as I review `CoordinateRange` today. I'll commit changes to this PR as I go and merge shortly.

Thanks again for your work on this PR, and all the other ones up until now! You've done a lot of great work to make this library awesome 🚀 ✨

**Comment by idotta** [comment]
Is there a reason for `CoordinateRange.Center` being removed or was it a mistake while refactoring? I was using it before.

**Comment by swharden** [comment]
Seems like a mistake! It should definitely be there 😅 

Ideally with a test to make sure it doesn't get removed accidentally again 🤪

**Comment by idotta** [comment]
I'll try to make a PR to fix it asap then. Thanks!

**Pull request merged**
