### PR TITLE
Improve spline shape

### PR DESCRIPTION
**Pull request by drolevar**
This fix gives better shape around endpoint in an open spline.

### CODE REVIEW

**Comment by swharden** [comment]
Thanks for this PR @drolevar! The difference looks pretty small. Do you have a shape you recommend trying to best showcase the change?

before | after
---|---
image|image


before | after
---|---
image|image

**Comment by drolevar** [comment]
@swharden It is indeed very small, but you can look for example at the top end of the orange curve (tension 0.3).

**Comment by swharden** [comment]
Wow, it's so subtle! How did you realize it was incorrect? 😅 Thanks for the fix either way!

## Before
spline-before

## After
spline-after

**Comment by drolevar** [comment]
@swharden Because I knew that both options are possible, and later I decided that the second is better :)

**Pull request merged**
