### PR TITLE
Use WriteableBitmap to improve performance of WPF rendering

### PR DESCRIPTION
**Pull request by jbuckmccready**
Added use of a WriteableBitmap to avoid unneeded allocations and rebinding the image element source when the backend bitmap is only updated (not changed)

**Purpose:**
Improves performance of WPF rendering and fixes https://github.com/ScottPlot/ScottPlot/issues/1387.

### CODE REVIEW

**Comment by bclehmann** [comment]
> OK I cleaned it up - feel free to squash the commits before merge or let me know if you want me to.

We don't normally squash PRs into one commit, so I think that's ok.

**Comment by bclehmann** [comment]
Also, it's worth noting that this enhancement could likely be made to WinForms and Avalonia. Non-Windows platforms don't have `System.Windows.Media.Imaging.WritableBitmap`, but Avalonia seems to offer an [alternative](http://reference.avaloniaui.net/api/Avalonia.Media.Imaging/WriteableBitmap/).

**Comment by swharden** [comment]
> Non-Windows platforms don't have `System.Windows.Media.Imaging.WritableBitmap`, but Avalonia seems to offer an [alternative](http://reference.avaloniaui.net/api/Avalonia.Media.Imaging/WriteableBitmap/).

I don't want to reinvent the wheel here... but is this something we could implement ourselves? The [BMP file format](https://en.wikipedia.org/wiki/BMP_file_format) isn't that bad, and an obligate _writer_ could be more straightforward to implement than a _reader_ that would have to support multiple/nuanced file structures and header types.

> If you're interested that could become part of this or a later PR, or we can open an issue for someone to do that later.

I'm definitely interested in exploring this idea for the other two controls! A separate PR/issue sounds like a good idea because I see the warning sighs of a rabbit hole 😉

**Comment by swharden** [comment]
I'm going to test this now and hopefully merge it in tonight... Thanks @jbuckmccready for this PR, and @bclehmann for your input! 🚀 

> @swharden: but is this something we could implement ourselves? 

> @jbuckmccready: I didn't want to affect the backend API

I should have clarified https://github.com/ScottPlot/ScottPlot/pull/1388#issuecomment-948105381 was directed toward @bclehmann, and implementing an in-memory bitmap writer could be a goal for another issue/PR. This PR is looking great, and it certainly makes sense to use `System.Windows.Media.Imaging.WritableBitmap` for the WPF control 👍 

> utilizing the GPU to rasterize directly to a frame

I'm inclined away from this because I want to minimize the dependencies (software and hardware) this project takes on. If we went into GPU land there would be some interesting mathematical operations we could optimize too. I don't intend to go there any time soon (beyond Skia/OpenGL support for hardware-accelerated 2D drawing, #1036).

> It should be possible to reuse all the bitmap buffers involved until a resize event occurs and the bitmap buffer must be increased or decreased

ScottPlot actually does this under the hood (re-using a `System.Drawing.Bitmap` and drawing on it, creating a new one only when resized). 

> double swap type of architecture so the consumer is never blocked

Double-buffering is an excellent concept to consider! I added it to the triage list #1028 to revisit in the future. I did some early experiments with this long ago, but I think it's definitely worth reconsidering in the future.

Note that the primary `System.Drawing.Bitmap` that is re-used by ScottPlot is displayed as an `Image` in a `PictureBox` in the Windows Forms control. The `PictureBox` `Image` is double-buffered out of the box, allowing the WinForms control to update that image in some situations without blocking the UI thread.

**Pull request merged**
