### PR TITLE
FormsPlot: Plot Object Editor

### PR DESCRIPTION
**Pull request by swharden**
This PR adds a plot object editor to the default right-click menu. It leans on the WinForms [PropertyGrid](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.propertygrid) to provide a simple GUI for users to edit all public properties of plottables on the plot.

There is some danger here, as it may be possible to configure plottables to enter an unrenderable state.

On the other hand, if these properties were made safer, this may be a useful strategy to allow users to investigate what properties are available for customization.

This idea extends suggestions from @bradmartin333 and @BambOoxX in #1831

grid

### CODE REVIEW

**Comment by BambOoxX** [comment]
Very nice! What kind of properties can make the plottable non renderable? I'm pretty sure it's easy to break things but I can't find one at the moment...

**Comment by bradmartin333** [comment]
Nice! Setting a min window size for the Plot Object Editor form and using a table layout panel instead of custom anchoring could help for changes down the road. I was also unable to break it 👍

**Comment by swharden** [comment]
> What kind of properties can make the plottable non renderable? 

> I was also unable to break it

I set MinRenderIndex to 50 and MaxRenderIndex to 40 and it caused a hard crash 😈

Plottable objects were originally designed with the intent that developers (not end users) would directly modify the public properties, so safeguards were not placed to protect against highly irrational inputs. For this reason I don't think I'll expose the property editor by default, but I'll definitely include it in the next release behind a feature flag

> table layout panel instead of custom anchoring

Good idea! I'll do this an merge it in today

**Comment by swharden** [comment]
This opt-in feature can be enabled with:

```cs
formsPlot1.Configuration.EnablePlotObjectEditor = true;
```

**Comment by BambOoxX** [comment]
@swharden Would there be an easy way to filter properties? For instance the ones related to appearance (color, visibility... ) which should be unbreakable (or not?) and the ones related to data (renderindex, axis index... ) which are likely to break things?

I also belive that having the possibility to sort things (per plot type, per axis index, per label) would be of huge help when dealing with multiple objects

**Comment by bradmartin333** [comment]
`System.ComponentModel` allows for categories, descriptions and much more

```cs
private int _ColorRounding = 2;
[Category("User Parameters")]
[Description("The higher the number, the more colors are shown in the Z axis and the longer it will take to create the plot. Default = 2, Min = 0, Max = 10")]
public int ColorRounding
{
    get => _ColorRounding;
    set
    {
        if (value < 0)
            _ColorRounding = 0;
        else if (value > 10)
            _ColorRounding = 10;
        else
            _ColorRounding = value;
        MakePlots();
    }
}
```

The viewable attributes can be selected like this

```cs
PropertyGrid.BrowsableAttributes = new AttributeCollection(new CategoryAttribute("User Parameters"));
```

**Comment by BambOoxX** [comment]
Thanks for the tip @bradmartin333!

**Comment by swharden** [comment]
> categories, descriptions and much more

This is true! I disabled the description box because I don't currently utilize these attributes, but if added to properties they would appear in the property grid

* [CategoryAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.categoryattribute?view=net-6.0&viewFallbackFrom=windowsdesktop-6.0)
* [DescriptionAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.descriptionattribute?view=net-6.0&viewFallbackFrom=windowsdesktop-6.0)

At first my thought was to omit these because I assumed they were in the `System.Windows.Forms`, but looking closer I now see they are in the [`System.ComponentModel` Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel?view=net-6.0) so it would be possible to sprinkle these in the core ScottPlot library.

Presently most properties have XML documentation to indicate what they do and how to use them, and I think this is most useful as it appears in the IDE when interacting with properties. Coping that text into a bunch of attributes would be a lot of duplication, and contents of those attributes don't seem to be available as hints in code editors.

**Comment by swharden** [comment]
> legend item in the plot object list 

Good idea! I started #1846 to remind me to make that change. If you want to create a PR to implement this you're welcome to, otherwise I'll leave it open and get to it in a few days 👍

**Comment by BublilDaniel** [comment]
Hi
any way to add this into WpfPlot as well?

**Pull request merged**
