### PR TITLE
Markers: refactor

### LINKED ISSUE #1668: Markers: Render without using DrawString()
In #1660 @BambOoxX created an optimized marker rendering system that does not use `DrawString()`.

This may require extensive testing (#1666/#1667), so in an effort to keep #1660 moving forward I'm cutting this code out of that PR and pasting it here so it can be possibly added as a future PR.

<details>
<summary>full code</summary>

```cs

public static void DrawMarkersNew(Graphics gfx, ICollection<PointF> pixelLocations, MarkerShape shape, float size, Color color)
{
	if (size == 0 || shape == MarkerShape.none)
		return;

	Pen pen = new Pen(color);

	Brush brush = new SolidBrush(color);

	float halfsize = size / 2;
	float halfsqrt3size = (float)0.866 * size;
	float halfsqrt2size = (float)0.707 * size;

	// adjust marker offset to improve rendering on Linux and MacOS
	float markerOffsetX = (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) ? 0 : 1;
	switch (shape)
	{
		case MarkerShape.filledCircle:
			foreach (PointF point in pixelLocations)
			{
				gfx.FillEllipse(brush: brush, x: point.X - halfsize + markerOffsetX, y: point.Y - halfsize, width: size, height: size);
			}

			break;
		case MarkerShape.openCircle:
			foreach (PointF point in pixelLocations)
			{
				gfx.DrawEllipse(pen: pen, x: point.X - halfsize + markerOffsetX, y: point.Y - halfsize, width: size, height: size);
			}

			break;
		case MarkerShape.filledSquare:
			foreach (PointF point in pixelLocations)
			{
				gfx.FillRectangle(brush: brush, x: point.X - halfsize + markerOffsetX, y: point.Y - halfsize, width: size, height: size);
			}

			break;
		case MarkerShape.openSquare:
			foreach (PointF point in pixelLocations)
			{
				gfx.DrawRectangle(pen: pen, x: point.X - halfsize + markerOffsetX, y: point.Y - halfsize, width: size, height: size);
			}

			break;
		case MarkerShape.filledDiamond:
			foreach (PointF point in pixelLocations)
			{
				// Create points that define polygon.
				PointF point1 = new PointF(point.X + markerOffsetX, point.Y + halfsize);
				PointF point2 = new PointF(point.X + markerOffsetX - halfsize, point.Y);
				PointF point3 = new PointF(point.X + markerOffsetX, point.Y - halfsize);
				PointF point4 = new PointF(point.X + markerOffsetX + halfsize, point.Y);

				PointF[] curvePoints = { point1, point2, point3, point4 };

				//Fill polygon to screen
				gfx.FillPolygon(brush, curvePoints);
			}

			break;
		case MarkerShape.openDiamond:
			foreach (PointF point in pixelLocations)
			{
				// Create points that define polygon.
				PointF point5 = new PointF(point.X + markerOffsetX, point.Y + halfsize);
				PointF point6 = new PointF(point.X + markerOffsetX - halfsize, point.Y);
				PointF point7 = new PointF(point.X + markerOffsetX, point.Y - halfsize);
				PointF point8 = new PointF(point.X + markerOffsetX + halfsize, point.Y);

				PointF[] curvePoints2 = { point5, point6, point7, point8 };

				//Draw polygon to screen
				gfx.DrawPolygon(pen, curvePoints2);
			}

			break;
		case MarkerShape.asterisk:
			//Font drawFont = new Font("CourierNew", size * 3);
			//SizeF textSize = Drawing.GDI.MeasureString(gfx, "*", drawFont);
			//float halfWidth = textSize.Width / 2;
			//float quarterHeight = textSize.Height / 4;
			foreach (PointF point in pixelLocations)
			{
				//gfx.DrawString("*", drawFont, brush, point.X - halfWidth, point.Y - quarterHeight);
				// horizontal line of the *
				gfx.DrawLine(pen, point.X + markerOffsetX - halfsize, point.Y, point.X + markerOffsetX + halfsize, point.Y);
				// vertical line of the *
				gfx.DrawLine(pen, point.X + markerOffsetX, point.Y - halfsize, point.X + markerOffsetX, point.Y + halfsize);
				// bottom-left / top-right line of the *
				gfx.DrawLine(pen, point.X + markerOffsetX - halfsqrt2size, point.Y - halfsqrt2size, point.X + markerOffsetX + halfsqrt2size, point.Y + halfsqrt2size);
				// top-left / bottom-right line of the *
				gfx.DrawLine(pen, point.X + markerOffsetX - halfsqrt2size, point.Y + halfsqrt2size, point.X + markerOffsetX + halfsqrt2size, point.Y - halfsqrt2size);
			}

			break;
		case MarkerShape.hashTag:
			Font drawFont2 = new Font("CourierNew", size * 2);
			SizeF textSize2 = Drawing.GDI.MeasureString(gfx, "#", drawFont2);
			float halfWidth2 = textSize2.Width / 2;
			float quarterHeight2 = textSize2.Height / 4;
			foreach (PointF point in pixelLocations)
			{
				gfx.DrawString("#", drawFont2, brush, point.X - halfWidth2, point.Y - quarterHeight2);
			}

			break;
		case MarkerShape.cross:
			//Font drawFont3 = new Font("CourierNew", size * 2);
			//SizeF textSize3 = Drawing.GDI.MeasureString(gfx, "+", drawFont3);
			//float halfWidth3 = textSize3.Width / (5 / 2);
			//float quarterHeight3 = textSize3.Height / 2;
			foreach (PointF point in pixelLocations)
			{
				//gfx.DrawString("+", drawFont3, brush, point.X - halfWidth3, point.Y - quarterHeight3);
				// horizontal line of the +
				gfx.DrawLine(pen, point.X + markerOffsetX - halfsize, point.Y, point.X + markerOffsetX + halfsize, point.Y);
				// vertical line of the +
				gfx.DrawLine(pen, point.X + markerOffsetX, point.Y - halfsize, point.X + markerOffsetX, point.Y + halfsize);
			}

			break;
		case MarkerShape.eks:
			//Font drawFont4 = new Font("CourierNew", size * 2);
			//SizeF textSize4 = Drawing.GDI.MeasureString(gfx, "x", drawFont4);
			//float halfWidth4 = textSize4.Width / (5 / 2);
			//float quarterHeight4 = textSize4.Height / 2;
			float sqrt2size = (float)1.414 * size;
			foreach (PointF point in pixelLocations)
			{
				//gfx.DrawString("x", drawFont4, brush, point.X - halfWidth4, point.Y - quarterHeight4);
				// bottom-left / top-right line of the x
				gfx.DrawLine(pen, point.X + markerOffsetX - sqrt2size, point.Y - sqrt2size, point.X + markerOffsetX + sqrt2size, point.Y + sqrt2size);
				// top-left / bottom-right line of the x
				gfx.DrawLine(pen, point.X + markerOffsetX - sqrt2size, point.Y + sqrt2size, point.X + markerOffsetX + sqrt2size, point.Y - sqrt2size);
			}

			break;
		case MarkerShape.verticalBar:
			//Font drawFont5 = new Font("CourierNew", size * 2);
			//SizeF textSize5 = Drawing.GDI.MeasureString(gfx, "|", drawFont5);
			//float halfWidth5 = textSize5.Width / (5 / 2);
			//float quarterHeight5 = textSize5.Height / 2;
			foreach (PointF point in pixelLocations)
			{
				//gfx.DrawString("|", drawFont5, brush, point.X - halfWidth5, point.Y - quarterHeight5);
				// vertical line of the *
				gfx.DrawLine(pen, point.X + markerOffsetX, point.Y - halfsize, point.X + markerOffsetX, point.Y + halfsize);
			}

			break;
		case MarkerShape.triUp:
			foreach (PointF point in pixelLocations)
			{
				// Create points that define polygon.
				PointF point9 = new PointF(point.X + markerOffsetX, point.Y - size);
				PointF point10 = new PointF(point.X + markerOffsetX, point.Y);
				PointF point11 = new PointF(point.X + markerOffsetX - halfsqrt3size, point.Y + halfsize);
				PointF point12 = new PointF(point.X + markerOffsetX, point.Y);
				PointF point13 = new PointF(point.X + markerOffsetX + halfsqrt3size, point.Y + halfsize);

				PointF[] curvePoints3 = { point12, point9, point10, point11, point12, point13 };

				//Draw polygon to screen
				gfx.DrawPolygon(pen, curvePoints3);
			}

			break;
		case MarkerShape.triDown:
			foreach (PointF point in pixelLocations)
			{
				// Create points that define polygon.
				PointF point14 = new PointF(point.X + markerOffsetX, point.Y + size);
				PointF point15 = new PointF(point.X + markerOffsetX, point.Y);
				PointF point16 = new PointF(point.X + markerOffsetX - halfsqrt3size, point.Y - halfsize);
				PointF point17 = new PointF(point.X + markerOffsetX, point.Y);
				PointF point18 = new PointF(point.X + markerOffsetX + halfsqrt3size, point.Y - halfsize);

				PointF[] curvePoints4 = { point17, point14, point15, point16, point17, point18 };

				//Draw polygon to screen
				gfx.DrawPolygon(pen, curvePoints4);
			}

			break;
		case MarkerShape.none:
			break;
		default:
			throw new NotImplementedException($"unsupported marker type: {shape}");
	}
}
```

</details>

### PR DESCRIPTION
**Pull request by swharden**
Currently `MarkerShape` is an `enum` and `DrawMarker()` uses a nasty `switch` to draw each marker.

Eventually (either here or ScottPlot 5) I want `Marker` objects to be classes that inherit `IMarker` and can `Draw()` themselves. This will make the code easier to maintain, make it easier to add new markers, and allow users to add their own custom markers too.

This PR will start by breaking apart the `RenderMarker()` method into smaller static methods, and explore options for moving toward a class-based marker system that minimizes breaking changes. Drawing routines will be optimized where appropriate. Resolves #1668

### CODE REVIEW

**Comment by swharden** [comment]
@BambOoxX you might get a kick out of seeing where this is now.

I'm going to try some deeper refactoring tomorrow, but now your core suggestion from #1660 of discretely drawing lines instead of placing text has been implemented 🚀 

before | after
---|---
image|image

I reduced the size where necessary to make sure all the markers are the same size

**Comment by BambOoxX** [comment]
@swharden Very nice! The only one I would modify is the asterisk. I believe reducing the length of the diagonal lines by a sqrt(2) factor would make the marker *rounder*.

**Comment by BambOoxX** [comment]
I think it would be good that hollow / thin markers inherit the line width, in order to maintain consistency. I will try to add that and also the two marker types proposed in #1660 initially

**Comment by BambOoxX** [comment]
Here a the new markers from #1689 

image

**Comment by BambOoxX** [comment]
Regarding the `DrawMarkers` method, my idea was focused at removing all the brush / pen creation from the loops as advised in 
https://stackoverflow.com/a/1961966/9576551

**Comment by swharden** [comment]
> my idea was focused at removing all the brush / pen creation from the loops as advised...

This is a good point indeed! I'll keep refactoring the Marker system today and favor brush/pen re-use where possible.

...but t be honest I'm not terribly motivated to micro-optimize GDI rendering at this time since my biggest active goal right now is cutting GDI out of this library entirely (#1036). My coding goal for now is aimed at making rendering methods as easy to port to another rendering system as possible.

**Comment by BambOoxX** [comment]
@swharden I see you are moving a lot of stuff around. I'll let you finish this then open a new PR with the following modifications (that I implemented at the moment) unless you don't think they are relevant.

- Add a `MarkerLineWidth` property to `IHasMarker` (or the equivalent stuff handling markers), and correct the plottables implementing `IHasMarker`.
- Improve `DrawMarker` and subsequent methods so that they take the `MarkerLineWidth` into account to plot the makers
- improve `LegendItem` so that there is no overflow of markers or linewidths (currently this is handled by `isRectangle` but that leads to not plotting a maker ever if there is one for large `LineWidth` values)
- Make `MarkerSize` and `MarkerLineWidth` depend on the `LineWidth` value in order to keep consistency (by default) between those values

**Comment by swharden** [comment]
This landed in a weird spot. All markers are classes now which is a step in the right direction, but it wasn't easy to swap-out `MarkerShape` from an `enum` to a `struct` or `class` because lots of ScottPlot code uses `MarkerShape` arguments with default values (something you can't do with these other types) so if I made the change it would break a lot of existing code... so I had to stop just short of my original goal.

The current solution is a little wonky but it works, doesn't break existing code, and these classes are ready to pick-up in ScottPlot 5 where breaking changes will be permitted.

https://github.com/ScottPlot/ScottPlot/blob/d8af928f57f8eb4d8b18a246a5f599f5ecade1e8/src/ScottPlot/Marker/Marker.cs#L32-L56

https://github.com/ScottPlot/ScottPlot/blob/d8af928f57f8eb4d8b18a246a5f599f5ecade1e8/src/ScottPlot/Marker/MarkerTools.cs#L10-L27

> I see you are moving a lot of stuff around. I'll let you finish this then open a new PR with the following modifications (that I implemented at the moment) unless you don't think they are relevant.

@BambOoxX I'm going to merge this now, and if you'd still like to make these changes given the new class structure you're welcome to in a new PR 👍 🚀

**Comment by BambOoxX** [comment]
> I'm going to merge this now, and if you'd still like to make these changes given the new class structure you're welcome to in a new PR 👍 🚀

All right it's on !

**Pull request merged**
