### PR TITLE
FormsPlot: dispose the Plot when the handle is destroyed

### PR DESCRIPTION
**Pull request by bwedding**
#3589 

The issue was, when the dialog was closed, Plot was not being disposed when the HandleDestroyed fired, which it did when the user X'd out of the dialog. It only disposed the SKElement. 

This was tested on the user-supplied test project. 

image

### CODE REVIEW

**Comment by swharden** [comment]
Hi @bwedding, thanks for this PR!

Unfortunately there's a bit of a roadblock here... This pull request contains _hundreds_ of modified files, and over a _million_ lines of added code. It's pretty hard to understand what the proposed code change is 😅 

modified files | changed lines of code
---|---
image|image

**Comment by swharden** [comment]
> over a million lines of added code

It looks like the `.sonarqube` folder was accidentally committed. The core change proposed change is here:

image

I'll update this PR by deleting that extra folder and merging this in. Thanks for the fix! 🚀

**Comment by bwedding** [comment]
Sorry about the SonarQube thing. I didn't see that it was added.

**Comment by swharden** [comment]
> Sorry about the SonarQube thing. I didn't see that it was added.

No worries! I'm relieved to learn the fix to the issue didn't actually require 1.4 million lines of code 😜 This was a great fix, thanks again! 🚀

**Pull request merged**
