### PR TITLE
SP5: Line (new plot type)

### LINKED ISSUE #2915: SP5: `Line` plot type
I'm about to merge #2901 which provides methods like `Add.Line()` to place a line on the plot, but the way it does it is by creating a scatter plot with only two points. This gets the job done for now, but a special `Line` plot type just for straight lines seems like a better option. A primitive that represents a single line would also be useful to have.

### PR DESCRIPTION
**Pull request by Gray-lab**
**Purpose:**
* Resolves #2915 
* Add Line primitive
* Add LinePlot plot type
* Add Cookbook entry for Line plot
* Add RandomLinePattern method to Generate

The results of the cookbook plots - I used the Marker cookbook plots as a template:
LineQuickStart
LinePlotStyles
LinePlotLegend

### CODE REVIEW

**Comment by Gray-lab** [comment]
I am not sure what is causing the crash during the Test on Windows - it isn't happening locally. I will keep looking into it but I am not sure yet.

**Comment by swharden** [comment]
Hi @Gray-lab, thanks for this PR it looks awesome!

Tests run fine on my computer too... Issues specific to the CI system are difficult to troubleshoot but I'll look into it now.

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SkiaSharp.SKAbstractManagedWStream.WriteInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
   at SkiaSharp.SkiaApi.sk_canvas_destroy(IntPtr param0)
   at SkiaSharp.SKCanvas.DisposeNative()
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKCanvas.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()
```

**Comment by swharden** [comment]
> Issues specific to the CI system are difficult to troubleshoot

after re-running the tests they pass now 🤷 

I made a few small changes and am about to merge this in. Thanks again! 🚀

**Comment by Gray-lab** [comment]
Thank you so much! I was at a loss as to how to troubleshoot and suspected it might have been something transient. Also thank you for the positive feedback! :)

**Pull request merged**
