### PR TITLE
SP5: Improve Blazor Cookbook

### PR DESCRIPTION
**Pull request by KroMignon**
This is a very small PR and **unfinished**.

Sorry for that, but I cannot test the changes, hope this could help to solve some bugs on Blazor Cookbook application.

I add comment in code, to help to understand the way it should be used (cf https://github.com/ScottPlot/ScottPlot/issues/3664#issuecomment-2071671044)

### CODE REVIEW

**Comment by swharden** [comment]
Hi @KroMignon, thanks for these refinements! This PR has been open for a little over a month and I'm inclined to merge it in soon, but I didn't want to before I checked with you because I see it's still marked draft.

What do you think about me merging it in now and creating new PRs later vs. leaving this one open for longer? Alternatively you could keep working in your own branch and only open a PR when you're closer to having it ready to review.

**Comment by KroMignon** [comment]
Hello @swharden, 
Please do not merge this PR now, it is not a good point to do it.
I am very busy at time, but I will try to finish it in the next couple of days.

**Comment by swharden** [comment]
> Hello @swharden, Please do not merge this PR now, it is not a good point to do it. I am very busy at time, but I will try to finish it in the next couple of days.

Sounds good! Take as long as you need, and if there will be a long break in working on it we can always close it and open it up again 👍

**Comment by swharden** [comment]
I'm going to close this for now, but we can open it up again when it's closer to being ready to merge.

I'll add a note in #3664 to look at this branch when I start working on the Blazor demo again, so if you remain busy I will probably merge this in eventually.

Thanks again for your effort on this PR!

**Comment by KroMignon** [comment]
Bad timing!
I had made some modifications on this PR but could not merge my branche because PR is closed 🙃 

Could you reopen it?

My PR is not the cleanest way to do, but it "works" and Blazor App can also run on smaller screens like smartphone.

**Comment by swharden** [comment]
> Could you reopen it?

My bad! I thought if I closed it you could re-open it.

Thanks for all the work you did here and for your patience as I continue to learn how to navigate GitHub 😅

**Comment by KroMignon** [comment]
Hi @swharden ,

this is not the very cleanest way to handle it, but at least "it works"... 🫤 
I am not a Blazor / CSS specialist, perhaps someone with more knowledge / experience could finish/polish it.

I change change to title to remove "WIP" but I can not change the label.

**Comment by swharden** [comment]
Hi @KroMignon, thanks for these improvements! I was about to merge this in but I noticed that resizing the plot causes it to "flicker" as `Reset()` is called several times. I don't mind the visual artifacts, but I noticed that if I left-click-drag to pan while it is still flickering (resizing) it throws an exception.

Do you have a recommended strategy for preventing user inputs while the plot is resetting?

**Comment by KroMignon** [comment]
That sounds bad.
Blazor / WASM / JavaScript needs to be asynchronous to be "reactive", this looks like an threading issue.
Perhaps the quickest way to work around this would be to remove the direct refresh.
While a rendering is in progress, store new rendering request and start it when current rendering is done.

**Comment by swharden** [comment]
I made some changes which fixed the interactivity-during-resizing issue and also made the automatic resizing an opt-in feature 👍 

https://swharden.com/tmp/sp/11/

**Pull request merged**
