### PR TITLE
Callout: new plot type

### PR DESCRIPTION
**Pull request by NicolasLairNET**
This pull request add new Plot named LabelPlot which allows to create a Label draggable with a link an element

https://github.com/ScottPlot/ScottPlot/assets/20141074/ead17b59-446f-4e30-8c7d-fdd51e3fb676

 See issue https://github.com/ScottPlot/ScottPlot/issues/3420 for more context.

```cs
using ScottPlot;
using ScottPlot.Plottables;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    LabelPlot? labelBeingDragged = null;
    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.Axes.SetLimits(-1, 10, -1, 1);
        var label = formsPlot1.Plot.Add.LabelPlot(
            "A beautiful draggable label\nCan be link with an element", 
            3, 
            0, 
            3, 
            0);

        label.Label.BorderColor = Colors.Blue;
        label.Label.BackColor = Colors.Blue.WithAlpha(.5);
        label.Label.Padding = 5;

        label.LineStyle = new LineStyle()
        {
            Color = label.Label.BorderColor,
            Width = label.Label.BorderWidth,
        };

        formsPlot1.MouseDown += FormsPlot1_MouseDown;
        formsPlot1.MouseUp += FormsPlot1_MouseUp;
        formsPlot1.MouseMove += FormsPlot1_MouseMove;
    }

    private void FormsPlot1_MouseMove(object? sender, MouseEventArgs e)
    {
        if (labelBeingDragged is null) return;
        labelBeingDragged.Move(e.X, e.Y);
        formsPlot1.Refresh();
    }

    private void FormsPlot1_MouseUp(object? sender, MouseEventArgs e)
    {
        labelBeingDragged = null;
        formsPlot1.Interaction.Enable();
        formsPlot1.Refresh();
    }

    private void FormsPlot1_MouseDown(object? sender, MouseEventArgs e)
    {
        LabelPlot? labelUnderMouse = GetLabelUnderMouse(e.X, e.Y);
        if (labelUnderMouse is not null)
        {
            labelBeingDragged = labelUnderMouse;
            labelBeingDragged.StartMove(e.X, e.Y);
            formsPlot1.Interaction.Disable();
        }
    }

    private LabelPlot? GetLabelUnderMouse(float x, float y)
    {
        foreach (LabelPlot label in formsPlot1.Plot.GetPlottables<LabelPlot>())
        {
            if (label.IsUnderMouse(x, y)) return label;
        }

        return null;
    }
}
```

### CODE REVIEW

**Comment by NicolasLairNET** [comment]
Hi @swharden could you give me your opinion about on my PR and I don't understand why PR check failed.

**Comment by swharden** [comment]
> Hi @swharden could you give me your opinion about on my PR and I don't understand why PR check failed.

Hey @NicolasLairNET, thanks for this PR it's looking awesome! I'm on my phone so I'll be brief. The error message is buried deep in there ...

```
System.InvalidOperationException : PlottableAdder.cs methods must be in alphabetical order. Line is currently before LabelPlot
```

**Comment by drphobos** [comment]
Hi @NicolasLairNET,

The build pipeline runs unit tests to check that everything is working and one of them failed.
The method that failed is Test_AddMethods_AreAlphabetized which practically fails if in the PlottableAdder.cs file all methods are not in alphabetical order (except GetNextColor method).
Try to put LabelPlot methods before Line methods.

**Comment by swharden** [comment]
Looks like you figured out the build checks! I'm going to take over and make a few refinements then merge this in.

I'll rename this plot type to "callout". I found something similar as a Powerpoint shape and they call it a callout, and I like the idea of keeping the plottable name distinct from the primitive name.

image

Thanks again for this great new features! I'm excited to have it in the next release 🚀

**Comment by NicolasLairNET** [comment]
Thanks @swharden. The new name is perfect, I'm French and I couldn't find a good name for this new plot.

**Comment by swharden** [comment]
Note I'm also taking inspiration from matplotlib as I refactor a bit
https://matplotlib.org/stable/gallery/text_labels_and_annotations/annotation_demo.html

image

**Comment by swharden** [comment]
I also lost an hour working on #3657 to make that curve to demonstrate this new plot type 😆

When it's done it's going to look great! 🚀 

image

**Comment by swharden** [comment]
This is looking fantastic! Merging now 🚀 🚀 🚀

callout

**Pull request merged**
