### PR TITLE
New plottables - `DraggableMarkerPlot` and `DraggableMarkerPlotInVector`

### PR DESCRIPTION
**Pull request by BambOoxX**
- `DraggableMarkerPlot` is a `MarkerPlot` that can be dragged through a `Plot`. This can serve as a *static* way to pinpoint a location on the axes. By *static* I mean that does not move with the mouse unless dragged
- `DraggableMarkerPlotInVector` behaves somewhat similar to as `ScatterPlot` that in addition has a draggable point. When you drag the point, it goes to the coordinates in the vector closest to the mouse position.

### CODE REVIEW

**Comment by swharden** [comment]
Hi @BambOoxX, thank you for this interesting PR! I'll begin working on it after #1556 and #1557

I haven't read the code in detail yet but I'm curious - would it be possible to inherit [`MarkerPlot`](MarkerPlot.cs) and `IDraggable` to reduce a little bit of code duplication? This technique is exactly what I suggested for @anose001 in #1555 when this exact topic was raised in a discussion question earlier today.

**Comment by BambOoxX** [comment]
@swharden I just trie to use some inheritance, but for `DraggableMarkerPlotInVector` the draggable marker isn't plot anymore. This feels like the new `Render` is not taken into account.

**Comment by swharden** [comment]
Hi @BambOoxX, related to #1558 I got you started here by adding a cookbook example

screenshot-drag

I was confused at first because the default marker color is white and I thought it was a rendering failure but it turns out it was just white on white, but all looks good now!

I changed the marker type to `Hand` but if you want the user to be able to make it a `Crosshair` you could make it `{get;set;}` and default to `Hand`

Can you add a similar cookbook example to demonstrate DraggableMarkerPlotInVector? That use case is a little more complex but I'd like to see how you choose to showcase it. Thanks! 🚀

**Comment by BambOoxX** [comment]
> Can you add a similar cookbook example to demonstrate `DraggableMarkerPlotInVector`? That use case is a little more complex but I'd like to see how you choose to showcase it. Thanks! 🚀

I will try and do an example, I have in mind something close to `ShowValueOnHover` but with something draggable.

However, I can't understand why the marker is not plotted now in `DraggableMarkerPlotInVector`. Could you have a look at the `Render` method ? Is it the correct way to inherit from `ScatterPlot` ?

**Comment by swharden** [comment]
Hi @BambOoxX, thanks for this PR! It looks like you figured everything out and this is ready to merge. These new plot types will be available in the next release 👍 😎 🚀

**Pull request merged**
