### PR TITLE
Render Manger: wrap clipping functionality in an abstraction

### PR DESCRIPTION
**Pull request by BrianAtZetica**
This may be a risky PR to adopt - I never observed any issues, and couldn't identify any changes resulting form my code fixes. 
Nevertheless, the changes here address #3523, makign sure any call to cavas.Save() is ballanced by a call to canvas.Restore() and vice versa.

cavas.SaveCount seems to be limited to a minimum value of 1, making it difficult to recognise when there is an imbalance. 
I was able to verify that the code before was unballanced. To do this I inserted an additional canvas.Save() before the render actions and an additional canvas.Restore() after the render actions. 

```cs
        canvas.Save()
        Stopwatch sw = new();
        foreach (IRenderAction action in RenderActions)
        {
            sw.Restart();
            rp.Canvas.Save();
            action.Render(rp);
            rp.Canvas.Restore();
            actionTimes.Add((action.ToString() ?? string.Empty, sw.Elapsed));
        }
        canvas.Restore();
```
(note this was a temporary change not committed to code).

This way I could track the cavas.SaveCount after each render action, which should have started and ended on a value of 2.
Before my code changes, the SaveCount dropped to one during the RenderDataBackground action.
After the changes, it remains at 2 for all actions. 

I ran all tests, and didn't spot anythign odd on any of the png outputs. 
See what you think. I'll understnad if changes seem too risky/uncertain.

### CODE REVIEW

**Comment by swharden** [comment]
Thanks for looking into this @BrianAtZetica! I think I'll adapt this PR and implement a more heavy-handed approach. I recently added source code parsing capabilities to the test system, so I'll scan the code base and fail the build if anyone calls `canvas.Save()` directly 😈

Instead, I'll add a `Clipping` class to the `RenderPack` which manages save/restore with a counter to make sure we never overdo it.

I'll modify this PR now to add that functionality and merge it in later today if it works as expected 👍

**Comment by swharden** [comment]
oof... I accidentally "fixed" this code but committed to the wrong branch 😩 I'm sorry! I'll reverse these changes in #3525 and make the commits on this branch instead.

**Comment by swharden** [comment]
I think things are good now! I'm going to merge this PR, but I'd appreciate it if you could glance over it and make sure you like what you see! We can refine it as needed in future PRs 👍

**Comment by BrianAtZetica** [comment]
Thanks @swharden (and @chjrom for #3528).
I was punching way above my weight to even be poking around in this area of the code. 
Satisfied that my effort, if only raised awareness of a posisble issue. Don't really need any attribution for the change log.

**Pull request merged**
