### PR TITLE
DataStreamer2: Improve support for rotated plots

### PR DESCRIPTION
**Pull request by drolevar**
Implemented rotation support in DataStreamer2, as mentioned in #4085.

However, I'll need some ideas from @swharden about how to approach the inversion of the Y axis to support top-down logging.

### CODE REVIEW

**Comment by drolevar** [comment]
@swharden Is there any existing functionality to invert the X/Y axis here? I see some examples with AutoScaler.InvertY, but I don't see a good way to apply it here.

**Comment by drolevar** [comment]
@KroMignon Maybe you have some good ideas how to invert the Y axis here?

**Comment by KroMignon** [comment]
@drolevar I do not really spend time on this feature. But my idea would be to try to "move" this feature from plotables like `DataStreamer` up to axis manager.

To be more verbose about my idea:
Each plot contains an axis manager, which hods the horizontal and vertical axis of the plot.
Adding a rotation feature on axis manager would  allow to rotate any plotable.
Axis manager would contains a property, `Origine` to define the axis origine point:
- `BottomLeft` (default origine)
    * Horizontal axis are growing from left to rigth
    * Vertical axis are growing from bottom to top
- `BottomRight`: 
    * Horizontal axis are growing from right to left
    * Vertical axis are growing from bottom to top
- `TopLeft`: 
    * Horizontal axis are growing from left to rigth
    * Vertical axis are growing from top to bottom
- `TopRight`: 
    * Horizontal axis are growing from right to left
    * Vertical axis are growing from top to bottom

And a boolean property `FlipAxis` or `SwapAxis` to flip horizontal and vertical axis.

This way, any plotable could be drawn in any direction. But I don't know if it is good idea... What do you mean?

**Comment by drolevar** [comment]
Also added support for InvertX/InvertY properties, which should help implement #4085.

@Jofstera See the demo for DataStreamer2.

**Comment by swharden** [comment]
Hi @drolevar and @KroMignon, thanks for your help with this one! I'm a bit behind on messages (I got pretty deep into #4053 over the last couple weeks) but I'm just now getting to this and it looks great.

One small change I made is to replace the word "normalized" with "rectified", because I think "normalized" typically means representing a range from 0 to 1.

I'm happy this will be in an upcoming release! Eventually we can figure out how to merge the experimental data streamer with he standard one, but this is a good fix in the interim

**Comment by drolevar** [comment]
@swharden Yes, I'd definitely want to figure out how to take it out of "Experimental". IMO everything possible with DataStreamer is possible with the new one, except for one property, which I will commit soon.

**Comment by drolevar** [comment]
@swharden I see that DataStreamer2 is much more compatible in terms of architecture with DataLogger than DataStreamer.
So basically if one creates a DataStreamer2 with a standard List<double> the result is more or less the same as with DataLogger.
One also doesn't really need the IDataStreamer2Source interface, since the variability is provided by the actual type of the `IList<Coordinates> coordinates`.

So one can keep DataStreamer as it is, and replace DataLogger with DataStreamer2 (with minor adjustments) and I don't think it will cause any disruptions. I can try that.

**Pull request merged**
