### PR TITLE
Demo: detachable legend and click-to-toggle-visibility

### PR DESCRIPTION
**Pull request by BambOoxX**
Adds a demo example for the detacheable legend control + plot modification options.

What remains to be done

- [x] properly setup de demo : need help to structure the example with an additional control for the legend viewer (need help @swharden)
- [x] include the detached legend options and features in the appropriate control
- [x] figure how to track toggling of visibile / invisible plots (see suggestions in #3842
- [ ] figure how to handle plots without text in legend
- [x] figure how to change painting of legend item based on toggled state of the plottable
- [x] figure how to handle legend resize
- [x] properly restore initial legend state upon detached legend closing
- [ ] trigger detached legend update after a modification

### CODE REVIEW

**Comment by BambOoxX** [comment]
@swharden If you could just setup the demo example properly so that an additional control can be created for the legend viewer that would be great. I really don't know how to do that correctly.

**Comment by swharden** [comment]
> @swharden If you could just setup the demo example properly so that an additional control can be created for the legend viewer that would be great. I really don't know how to do that correctly.

Sorry for the delayed response on this!

To get your app to appear in the list, make sure the `Form` inherits `IDemoWindow`, then it will show up automatically.

I'll go ahead and do this now and commit back to this branch...

**Comment by swharden** [comment]
Give it a try now! I also added a shortcut which can help during development: when the demo window first launches, press CTRL+D and your detachable legend window will open-up without you having to choose it from the list 👍

**Comment by swharden** [comment]
... give me a few more minutes and I'll get you started with a pop-up window and a skia canvas ...

**Comment by swharden** [comment]
All right @BambOoxX, some of my changes so far were a bit confusing, but this is a _really_ strong start. I'm excited to see what you're able to do from here! Maybe it's even close to done? 🚀

**Comment by BambOoxX** [comment]
@swharden Nice ! I'll have a look at this later. I'll keep you posted.

**Comment by BambOoxX** [comment]
@swharden I think I'm missing something, where is  the logic that handles the varying column / rows of `Legend` upon rendering located ? I could not find it...

**Comment by swharden** [comment]
> @swharden I think I'm missing something, where is the logic that handles the varying column / rows of `Legend` upon rendering located ? I could not find it...

https://github.com/ScottPlot/ScottPlot/blob/ab72fe6b4406aa84a5e5d203152e5c4ba6dd1dfa/src/ScottPlot5/ScottPlot5/Primitives/Legend.cs#L90

https://github.com/ScottPlot/ScottPlot/blob/ab72fe6b4406aa84a5e5d203152e5c4ba6dd1dfa/src/ScottPlot5/ScottPlot5/Primitives/Legend.cs#L214-L226

https://github.com/ScottPlot/ScottPlot/blob/32bc1432f620473dba23c36ce2054c450878d817/src/ScottPlot5/ScottPlot5/LegendLayouts/Wrapping.cs#L26-L40

**Comment by swharden** [comment]
I'm appreciating that this is not very simple 😅 

If it becomes too much, let me know and we can take a look together! I'm down to zoom if it helps.

**Comment by BambOoxX** [comment]
@swharden So the base is working. One can trigger visibility and change plottable properties, without actually tracking the plottables. The only compromise is that I had to add some methods in `Legend` to be visibility aware, otherwise the painted legend would have had masked plottables. Let me know what you think of these modifications. 

I still could not properly trigger updates of the detached legend yet, only of the Plot itself, except by changing the size of the control containing the detached legend.

**Comment by BambOoxX** [comment]
Last thing I believe is how to handle specific legend item cases. Since I don't use that functionality (yet), could you point me towards potentially problematic cases ?

**Comment by swharden** [comment]
Hey @BambOoxX, I have a little time right now... rather than me run this and try to figure out what's going on, do you have interest in hopping on a Zoom call where you can share your screen and show me what you've got going so far? I'm cool either way. If you're interested you can send me a DM on Discord and I'll send you a zoom link

**Comment by swharden** [comment]
> One can trigger visibility and change plottable properties, without actually tracking the plottables

> I still could not properly trigger updates of the detached legend yet

This looks pretty good! I have the code running on my box now and I'm taking a closer look...

detach

**Comment by swharden** [comment]
Ah, this is probably what you were asking:

```cs
private void LegendControl_SomeAction(SKControl sender, EventArgs ee)
            // TODO : How to trigger legend repaint ?
```

answer:

```cs
sender.Invalidate();
```

**Comment by swharden** [comment]
Hey @BambOoxX, I think I got this far enough that you can take it from here 🚀 

I'm not making any more edits to this branch until I hear back from you (to minimize risk of merge conflicts)

Let me know if you have further questions or if/when you think this is ready to merge! Thanks again for all your hard work on this -- these are some pretty advanced behaviors

detach2

**Comment by BambOoxX** [comment]
@swharden Nice ! There are still minor glitches with the markers that I have to sort out, but otherwise things look close to ready !

**Comment by swharden** [comment]
No rush, but let me know if you think this will be done in an hour or two and I will hold off making the next release until this is ready to merge.

I think the core changes to the main library have already been made, so if you want we could merge this now and you can continue to refine the demo later. Up to you!

**Comment by swharden** [comment]
No rush, but let me know if you think this will be done in an hour or two and I will hold off making the next release until this is ready to merge.

I think the core changes to the main library have already been made, so if you want we could merge this now and you can continue to refine the demo later. Up to you!

**Comment by BambOoxX** [comment]
I think you can release the rest without merging this for the moment, there is no rush. I'll try and finish this tomorrow. 
In the meantime, you could reopen #3842 to warn potentially interested people

**Comment by BambOoxX** [comment]
Also one thing that bothers me is that ideally the control should fit the legend, and  without shadow. Do you see a good way to do that ?

**Comment by swharden** [comment]
> Also one thing that bothers me is that ideally the control should fit the legend, and without shadow. Do you see a good way to do that ?

I think I can do this! I'll make some commits to this branch for the next several minutes.

> I think you can release the rest without merging this for the moment, there is no rush. I'll try and finish this tomorrow.

I recognize the remaining work is in the demo app (not the core library), so I'll modify this PR make the demo not appear in the demo list and you can take as long as you need to refine the demo, but I'll go ahead and merge this so I can release and not deal with long-running open branches that can be hard to merge later

Thanks again for all your work on this!

**Comment by swharden** [comment]
> I'll modify this PR make the demo not appear in the demo list and you can take as long as you need to refine the demo

Note that after 7c06c99de5ecb94bb719882b6797a419464524b2 it no longer appears in the list but CTRL+D will still launch it from the main screen of the demo app

**Comment by swharden** [comment]
image

**Comment by swharden** [comment]
> figure how to handle plots without text in legend

If you want to hack this in for now and we can come up with a more elegant solution later. I'm okay with a "magic value" that shows the shape but no text. Maybe something like

```cs
myScatterPlot.LegendText = "INTENTIONALLY_EMPTY";
```

You could get a little less hacky and make something like this:
```cs
// LegendItem.cs
public static string EmptyText = "{{empty}}";
```

```cs
// allowing users to do this
myScatterPlot.LegendText = LegendItem.EmptyText;
```

**Comment by BambOoxX** [comment]
@nilsakesson I'm not sure I understand your demand, could you elaborate ? There is definitely room for additional options.

**Comment by nilsakesson** [comment]
image

I made a WPF app with WPF native elements to invoke the events for the plot. Call it a "detachable legend" if you like. If there are multiple Signals in the same plot it's very convenient to change the y-axis of the signal in the options of it.

**Pull request merged**
