### PR TITLE
Plottable: IHasLine, IHasMarker, and IHlightable

### PR DESCRIPTION
**Pull request by BambOoxX**
This PR implements the interfaces discussed in #1655, which has been rebased on this branch (not sure if it was the right thing to do though). 
- Three new interfaces are created `IHasLine`, `IHasMarker` and `IIsHighlightable`. 
- A new marker plotting method `DrawMarkers` is proposed to support customizeable markers in `SignalPlot`s, as well as new implementations for marker plotting avoiding `DrawString` when possible. 
- Two new `MarkerShapes` are implemented : `openTriangle` and `filledTriangle`

Hopefully this will have some use beyond just interactive plotting.

### CODE REVIEW

**Comment by BambOoxX** [comment]
Here are some views of the new functionalities
- new markers (legend items are still ploted with the old functionnality)
https://user-images.githubusercontent.com/42067365/154061657-3be6e689-7f8a-4218-9eaa-48f77f1449fd.mp4
- SignalPlots with changeable markers
https://user-images.githubusercontent.com/42067365/154062260-2d66174d-7cd4-4fd6-8457-99908bbcdd26.mp4

**Comment by swharden** [comment]
> This PR implements the interfaces discussed in https://github.com/ScottPlot/ScottPlot/pull/1655, which has been rebased on this branch (not sure if it was the right thing to do though)

I'm not 100% on this either ... Inter-dependent PRs can get pretty complicated, especially if I decide to refactor the PR this one depends on.

My strategy will be to focus solely on #1655, refactor as necessary, merge it, then come back here, cross my fingers, and hold my breath and see what broke 😅 I recommend not making new commits on either of these PRs until I'm done working on them.

In the future, smallest-possible PRs are probably the solution to this 👍 E.g., refactoring the `DrawMarkers()` system, and also adding new marker types, each could have been their own PR (independent of adding interfaces to plottables).

You already did a lot of work (fantastic work!) here and in #1655, so I'll pick it up where it is and try to get it merged today or tomorrow 🤞

PS: In the next major version of ScottPlot (in a magical world with rainbows and unicorns, lol) each `Marker` would be a `class` and implement `IMarker` meaning it has a `Draw()` method. When each marker can draw itself, it's so much easier to add new markers, and there would be no switch statements! I look forward to this day 😄

**Comment by swharden** [comment]
I ran out of time and have to put this down tonight 😝

To be honest I got super overwhelmed with the modifications to the shape rendering code, so I took all of that out of this PR and stored it in #1660 so we can review it later when I have more availability to review/test it.

I think this PR is in a better/simpler place now, but I haven't had time to adequately test it yet, and testing on Linux and MacOS will be extremely important since we are twiddling with marker alignment and it's been a problem in the past (#340) 👍 

PS: Marker rendering will be significantly reworked in ScottPlot 5, so I'm not highly motivated to micro-optimize System.Drawing marker rendering routines at this time. My main goal is to avoid introducing new bugs or or changes to existing behavior.

Thanks again for your work on this @BambOoxX! Hopefully I can merge this tomorrow night 🚀

**Comment by BambOoxX** [comment]
> My strategy will be to focus solely on #1660, refactor as necessary, merge it, then come back here, cross my fingers, and hold my breath and see what broke 😅 I recommend not making new commits on either of these PRs until I'm done working on them.

Not problem with me, I was just surprised that `SignalPlots` could not change markers. So I just went on with it... Maybe a bit too enthusiastic on this one 😅...

> You already did a lot of work (fantastic work!) here and in #1655, so I'll pick it up where it is and try to get it merged today or tomorrow 🤞

Thanks, I'm just trying to help when I can. I saw an opportunity to try something...

> PS: In the next major version of ScottPlot (in a magical world with rainbows and unicorns, lol) each `Marker` would be a `class` and implement `IMarker` meaning it has a `Draw()` method. When each marker can draw itself, it's so much easier to add new markers, and there would be no switch statements! I look forward to this day 😄

Wouldn't that be problematic ? Some plots may have different markers depending on the point in the dataset, but for `ScatterPlot` and `SignalPlots` it seems better to have a single marker that is used throughout the dataset, no ?

**Comment by swharden** [comment]
> Thanks, I'm just trying to help when I can. I saw an opportunity to try something...

It's a good improvement! Lots of this work will translate to the next version of ScottPlot too 👍🚀 

> it seems better to have a single marker that is used throughout the dataset

This is true.... but perhaps I didn't describe my proposed change well here. 

Overall the the new behavior will be the essentially the same. 

I'll implement it soon in ScottPlot5 (e.g., `/dev/ScottPlot5` and #1647), then as we practice using the new design we will get an idea of whether it feels most natural or not

Since I'll be working in Marker land in #1668, it may be a good time to practice lightly refactoring ScottPlot 4's Marker rendering system to see if I can make it more modular without any breaking changes. I'll probably prioritize this over ScottPlot 5 development, and hopefully it'll be a quick refactor! Famous last words 🙃

**Comment by swharden** [comment]
@BambOoxX are you familiar with Docker? I'm struggling to run the unit tests in Linux in local docker container 
1a04aa8 😅 This would be helpful for confirming that marker rendering is accurate in Linux.

I can use WSL to run the tests locally for now, but a Docker solution would be much more elegant 🐋

**Comment by swharden** [comment]
I confirmed the pixel offset is still required when drawing circles on Linux 😝  #340

Looks like `0.5f` offset is better aligned than the `1.0f` used previously

Linux (no offset) | Linux (with offset)
---|---
Test_Plot_Basic_Linux|image

https://github.com/ScottPlot/ScottPlot/blob/21b11c943c6ac790b861f570042c0133f7169bfc/src/tests/Misc/OS.cs#L12-L30

Tested using WSL/ubuntu

image

**Comment by BambOoxX** [comment]
@swharden No, I have no clue about docker images. These always feel like magic to me 😅

**Comment by swharden** [comment]
> no clue about docker images

It was worth a shot!

@bclehmann your suggestion to run tests using WSL has been helpful. Do you have enough experience with Docker to know why the tests won't run in the dotnet SDK Docker image? (#1677)

**Comment by bclehmann** [comment]
> Do you have enough experience with Docker to know why the tests won't run in the dotnet SDK Docker image? (https://github.com/ScottPlot/ScottPlot/issues/1677)

The only things I can think of is either a native dependency isn't installed (i.e. libgdiplus) or if the dockerfile has conflicting dependency version requirements.

**Pull request merged**
