### PR TITLE
Signal: support inverted axes

### PR DESCRIPTION
**Pull request by Excustic**
Fixed issue  #3570 - enabling the option to invert axes of Signal plots.

- Added direction constants for inverting the axes in Signal plots. 
- Added GetVisibleYRange private method in Signal.
- Refactored variable names inside RenderLowDensity method of Signal.

image

### CODE REVIEW

**Comment by swharden** [comment]
Hi @Excustic, thanks for working on this! I'm about out of time right now so I can't take a closer look, but I can tell something's not exactly right because I'd expect the sine wave to be displayed in the X range between 0 and +50.

```cs
// this should display data from X = 0 to 50
WpfPlot1.Plot.Add.Signal(Generate.Sin());

// this inverts the X axis (so it goes from 50 down to 0)
WpfPlot1.Plot.Axes.SetLimitsX(50, 0);
```

image

If you're able to figure it out before I get to it again, feel free to update this PR! Otherwise I'll pick this up where I left off next time I'm free. Thanks again for helping out on this one! It will be great to have inverted axis support for signal plots 🚀

**Comment by Excustic** [comment]
I see, seems like it's a bit more complicated than I thought. It certainly requires refinement and further testing, I'll try to get on it next week and help you with it 👍

**Comment by Excustic** [comment]
I see, seems like it's a bit more complicated than I thought.

**Comment by swharden** [comment]
Figured it out! The code change required seems simple, but wow it took a lot to figure out. Thanks for getting this PR started @Excustic! I'm happy this new feature will be in the next release 🚀 

Note that this doesn't actually resolve #3570 because this PR addresses _signal_ plots but that issue is about _scatter_ plots

**Pull request merged**
