### PR TITLE
Axis: LockLimits()

### PR DESCRIPTION
**Pull request by swharden**
This PR adds methods to lock axes to prevent them from being panned/zoomed. Solves #1179

multi

### CODE REVIEW

**Comment by bclehmann** [comment]
The naming here sounds a little bit too similar to `AxisScaleLock`, at least to me.

Maybe `DisableInteractivity`? Let me know what you're thinking.

**Comment by swharden** [comment]
> The naming here sounds a little bit too similar to AxisScaleLock

Good point! I haven't done a deep dive into this topic yet, but according to #1197 some of the existing language results in unexpected behavior and may benefit from improvement.

I'm not totally sold on `DisableInteractivity()` because it's not clear if interactivity only applies to mouse events. I'm thinking a locked axis should remain unchanged if the axis limits are set manually or zoom/pan is called programmatically.

I agree with you `Lock()` is too ambiguous. Maybe `LockLimits()`?

**Comment by swharden** [comment]
@bclehmann what do you think of the new API and demos? 

Are you up for making the Avalonia demo or do you want me to do that? I'm cool either way

**Comment by bclehmann** [comment]
I don't mind doing it for Avalonia but I can't do it tonight. If you've already written a WPF version it's normally trivial to turn that into Avalonia.

**Comment by bclehmann** [comment]
I like the API, it looks like you avoided splitting it up so there could be different functions for disabling zoom and pan. I wonder if disabling pan but not zoom is a common usecase, if someone had a plot that was only drawn from x1 to x2 panning outside of that range is not useful.

It seems like that usecase would be better served by something like `RestrictTo(start, end)` or`RestrictTo(x1, y1, x2, y2)` anyways.

As for the demo, it seems fine, we mostly avoid MVVM elsewhere, I don't know if that was intentional or not? It is more WPF-ey, and I don't think it should be confusing to new people.

**Comment by swharden** [comment]
Thanks for your feedback @bclehmann!

> it looks like you avoided splitting it up into different functions for disabling zoom and pan

I left the door open to possibly implement more similar functions later:

* `LockSpan()` - allows min/max to change together but the delta remains fixed. Resizing the figure stretches the contents.

* `LockScale()` - keeps the units/pixel fixed. Resizing the figure does not change the scale of the contents.

> mostly avoid MVVM [in demos] ... intentional or not?

It usually is the result of making the demo first for WinForms then copy/pasting to realize the same effect in WPF as a code-behind. Admittedly demos that use designs idiomatic to each platform would be better, but are a little more work to create.

> I don't mind doing it for Avalonia but I can't do it tonight. If you've already written a WPF version it's normally trivial to turn that into Avalonia, so it's not much work either way.

No rush! If you're up for making the Avalonia demo that would be great. I can leave this PR open so you can create a PR into this branch, or I can merge this one into master and you can make a new branch/PR when you want - let me know what sounds good to you.

You're welcome to copy the WPF design (code-behind) or do something more idiomatic for Avalonia if you want to get fancy!

**Comment by bclehmann** [comment]
I made a PR. It's fairly similar to the WPF version. #1215

**Pull request merged**
