### PR TITLE
Update src/ScottPlot5/ScottPlot5/Primitives/PixelPadding.cs

### LINKED ISSUE #2874: PixelPadding: improve property names
`TotalHorizontal` should be just `Horizontal`

https://github.com/ScottPlot/ScottPlot/blob/42987b60b6fb90e94d0fb67a60c7dfafc73d8d9a/src/ScottPlot5/ScottPlot5/Primitives/PixelPadding.cs#L13-L14

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
**Purpose:**
* Use this space to describe what this pull request accomplishes
* If this PR references an issue be sure to link to it
* Consider including a picture if it would help clarify what this pull request does
* New contributors please review https://github.com/ScottPlot/ScottPlot/blob/main/CONTRIBUTING.md

```cs
// You can insert code examples like this
var newThing = new SpecialObject();
```

fix #2874

Hi [swharden](https://github.com/swharden),
just tying to help on this issue, please check it out

### CODE REVIEW

**Comment by swharden** [comment]
> just tying to help on this issue, please check it out

Awesome, thanks for working on this @viktoriussuwandi! 

I won't merge this in tonight, but definitely tomorrow 🚀

**Comment by viktoriussuwandi** [comment]
Hi @swharden,
Is there anything else need updated to merge this PR ? just lemme know :)

**Comment by swharden** [comment]
Thanks @viktoriussuwandi! Sorry this one took me so long to get to - I've been catching up on some other projects, but I'm back here now and merging this in 👍

**Comment by swharden** [comment]
image

😅😅😅

**Pull request merged**
