### PR TITLE
Always generate at least 2 major ticks (#1420)

### PR DESCRIPTION
**Pull request by bclehmann**
**Purpose:** #1420 

Note that this will create minor ticks even if there are no major ticks on-screen (but the minor ticks may be above or below the drawn area).

### 1 major tick visible
image

### 0 major ticks visible
image

### 0 major or minor ticks visible (zoomed in between minor ticks)
image

### CODE REVIEW

**Comment by bclehmann** [comment]
I still need to fix an issue where we can draw major ticks above the plotting area:

**Comment by bclehmann** [comment]
I noticed something while looking at this code: https://github.com/ScottPlot/ScottPlot/blob/1d1d8631b165b5f4549981941b048611ff753ab2/src/ScottPlot/Renderable/AxisTicks.cs#L72-L85

These function calls operate on predominantly the same data, but some of them take `double[]`, and some `TickCollection`. This could be prone to regressions or other bugs in the future, as they take different codepaths for restricting the ticks to only those that are visible.

**Comment by bclehmann** [comment]
I'm now realizing that this might still be broken in the case where the user set manual ticks rather than manual tick step.

I'll take another look tomorrow.

**Comment by swharden** [comment]
Hi @bclehmann, thanks for this PR! ... and sorry for my extreme delay. I moved to a new house this month and I got hit with way more disruption to my productivity than expected 😅 Things are starting to return to normal though!

I added some extra logic which adds extra integer ticks in the case that `IntegerPositionsOnly` removes too many ticks after reducing positions down to integers only (the original use case for #1420).

before | after
---|---
|1420b

**Comment by swharden** [comment]
> ... some of them take double[], and some TickCollection. This could be prone to regressions or other bugs in the future, as they take different codepaths for restricting the ticks to only those that are visible.

This warning is well-received! This is one of many serious issues with the present tick system. I'm going to prioritize refactoring the tick system soon (#1028) since official Maui.Graphics development is moving more slowly than anticipated.

**Pull request merged**
