### PR TITLE
Allow realtime updates of OHLC plots

### PR DESCRIPTION
**Pull request by CalderWhite**
**Purpose:**
I added in your suggested change from #827. Have been building it locally with my own project that uses ScottPlot and it works great!

**New Functionality:**
Adds the following to `FinancePlot.cs`:
```cs
public OHLC Last() => OHLCs.Last();
```

This allows users to mutate the last item of the list, allowing for realtime plotting updates.

**Notes:**

Although, I am unable to horizontally zoom the plot. Maybe the key bindings from that type of zoom have been changed in the beta, but that is unrelated.

I don't think I am being much help here since you already proposed the change, but at the very least I am using it and it works!

Thanks for the project, it's one of the few C# graphing libraries that has what I need and doesn't make me pay for it :)

### CODE REVIEW

**Comment by CalderWhite** [comment]
I think I haven't touched enough files. I am going to close this because of that.

**Comment by swharden** [comment]
Hi @CalderWhite,

I configured the build to fail if public properties/methods of plottables aren't documented with a `<summary>`. I recognize the error message is a bit cryptic and hard to get to. 

image

The feature in this PR looks useful! If you re-open this PR and add a summary so the build passes, I'd be happy to merge it 👍

**Comment by CalderWhite** [comment]
@swharden ah! thank you so much! I'll get right on it.

**Comment by swharden** [comment]
Sorry this one-liner turned-out to be so difficult! 😝

I suspect the code I wrote that asserts public methods are documented is getting stuck on this public _property_. I'll fix this shortly and merge this in 👍

**Comment by swharden** [comment]
In the original PR the XML docs were preceded by `//` instead of `///` so the summary wasn't being recognized.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/

I added the extra slashes and it seems to work now. This new feature will be in the next release I hope to put on NuGet in the next few days 🤞 

Thanks for the contribution @CalderWhite!

**Comment by CalderWhite** [comment]
Woo! If I do any more hacking I'll be sure to put up a PR :)

**Comment by swharden** [comment]
> Woo! If I do any more hacking I'll be sure to put up a PR :)

Sounds good! Sometimes what seems like a good idea as a developer is actually awkward for the user, so if you have any more ideas for how to smooth out the rough edges I welcome your feedback! 🚀

**Comment by ticool** [comment]
Hi im trying to use the  .Last();  by setting my new value (Hig, Low, etc) in this variable in my program loop !

OHLC lastPlot = CandlePlots.Last(); 
lastPlot.Low = 1234;
lastPlot.High= 4567;
.....

Im doing a  formsPlot1.Render() after, I tried formsPlot1.Refresh() too but the last candle doesn't refresh ! How do you use this ? Do you get an example plz !

**Comment by swharden** [comment]
Hi @ticool, 

It looks like `Last()` is a public method in the current version (4.1.16) of ScottPlot
https://www.fuget.org/packages/ScottPlot/4.1.16/lib/netstandard2.0/ScottPlot.dll/ScottPlot.Plottable/FinancePlot

Probably confirm you're running the latest public version and upgrade the package if a newer one is available, and let me know if this doesn't do the trick 👍

**Comment by swharden** [comment]
Hi @ticool, sorry about misunderstanding your question a moment ago.

After modifying the last `OHLC`, call `formsPlot1.Render()` to redraw that plot on the screen. Let me know if that doesn't do the trick! 👍

**Pull request merged**
