### PR TITLE
Multiplatform Sandbox: move projects into their own solution file

### PR DESCRIPTION
**Pull request by swharden**
#4223

### CODE REVIEW

**Comment by CoderPM2011** [comment]
`SkiaSharp` uses a "solution filter" to avoid solutions that are too large.
Maybe you can refer to it.

reference: 
1. https://learn.microsoft.com/en-us/visualstudio/msbuild/solution-filters?view=vs-2022
2. https://github.com/mono/SkiaSharp/tree/main/source

**Comment by swharden** [comment]
Good suggestion!

I did that a little while ago but it got really complicated. Some build tools, auto formatters, etc don't support that format. Also older versions of VS don't support that format.

Is there a way to have a solution where certain projects are "unloaded" by default? That could be a solution 🤔

**Comment by swharden** [comment]
Fundamentally, I think the sandbox projects are more "dev" or "doc" than "src" (from the perspective of the NuGet packages) so I'd like to think of a way to more elegantly separate them out...

**Comment by CoderPM2011** [comment]
> Fundamentally, I think the sandbox projects are more "dev" or "doc" than "src" (from the perspective of the NuGet packages) so I'd like to think of a way to more elegantly separate them out...

In fact, when I am developing, I will directly set the corresponding sandbox to the startup project.
After I modified the `ScottPlot5` code, I could directly execute the sandbox project and observe the results of the real-time modifications.😅

However, after splitting into two separate solutions, the `ScottPlot5` code cannot be viewed directly in the sandbox solution. 
Instead, one needs to switch between the two solutions.😥

---

There is another way.

Maybe you can create a dedicated `build configuration` for a specific target.
For example, when testing, only build some projects in the solution.😀

reference:
1. https://learn.microsoft.com/en-us/visualstudio/ide/understanding-build-configurations?view=vs-2022

**Comment by swharden** [comment]
> build configuration

Thanks for this suggestion! I'll try this today 👍

**Comment by swharden** [comment]
Great idea! Obvious in hindsight 😅 

image

Also, the .NET 9 preview terminal output is awesome

image

**Pull request merged**
