### PR TITLE
Scatter: improve cubic spline interpolation and expose SmoothTension property

### PR DESCRIPTION
**Pull request by drolevar**
Fix detection of consecutive segments. Previously segments were detected incorrectly, all NaN  points were just ignored.
Make tension consistent with a common definition.

### CODE REVIEW

**Comment by drolevar** [comment]
@swharden I wonder if introducing the new way of indexing arrays is OK with you.

**Comment by swharden** [comment]
Great fixes @drolevar, thanks so much!

Regarding the array code, I'm happy to include files like this to add modern language support to the older platforms we target as long as we keep the special features `internal`. 

Can you clarify where you obtained Index.cs? The file in this PR is a bit different than the one I found in the dotnet runtime repo https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Index.cs

**Comment by drolevar** [comment]
@swharden I got it from here: https://github.com/bgrainger/IndexRange
It's available as a Nuget package, but that would make it an extra dependency. The code gets anyway optimized out in release builds.

**Comment by swharden** [comment]
> It's available as a Nuget package, but that would make it an extra dependency. The code gets anyway optimized out in release builds.

Thanks for the clarification! I found a newer version of the file from an "official" source so I feel a little better about using that one. Either way, these little compiler niceties are great to have in the code base -- thanks!

**Comment by drolevar** [comment]
@swharden That new file doesn't have the necessary ##if guards for the newer versions, which leads to a lot of warnings.

**Comment by swharden** [comment]
Thanks for pointing that out @drolevar! If I'd implemented #3442 by now, I'd have caught that 😅

I'll mark #3442 high priory and both issues later today 👍

**Pull request merged**
