### PR TITLE
WinUI plot control

### PR DESCRIPTION
**Pull request by rafntor**
This PR adds ScottPlot.Uno.WinUI.UnoPlot multi-targeting control for Uno & WinUI(3)

Based on and should be equivalent to the existing ScottPlot.WPF.WpfPlot

Hopefully this does not collide with any other ongoing initiatives ;-) 
Solves https://github.com/ScottPlot/ScottPlot/issues/2039 ?

image

### CODE REVIEW

**Comment by rafntor** [comment]
Hmm, there is a build issue on github actions, not sure what that is really
"It builds on my machine" ;-)

**Comment by rafntor** [comment]
I also have a uno-webassembly project "Sandbox.Uno.Wasm" operational, but not added to the PR. (Can add if desired)
image
image

**Comment by swharden** [comment]
@rafntor Thank you ***so*** much for this PR! 

This looks fantastic and it worked beautifully right away on my system (after installing the "Windows App SDK" from https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads)

I'll merge this in tonight and start updating the website to indicate ScottPlot now supports WinUI3! 🚀

I'm definitely interested in your Wasm implementation, and invite you to open a PR whenever you think it's ready!

Thanks again for your hard work on this - I'm frequently impressed by how many high quality contributions emerge for this wonderful community!

**Comment by swharden** [comment]
@rafntor note that I changed some class names and namespaces to make this control more consistent with the naming of other controls:

namespace: `ScottPlot.Uno.WinUI` → `ScottPlot.WinUI`

class: `ScottPlot.Uno.WinUI.UnoPlot` → `ScottPlot.WinUI.WinUIPlot`

I understand that this WinUI implementation uses Uno, but my thought is that this implementation detail which end users probably don't need to see in the class names and namespaces. However I don't have much personal experience with WinUI, and although my goal was to make these names as simple as possible, if you think this is a mistake let me know and I can work to revert the change! Thanks for your input.

Resources:
* https://platform.uno/docs/articles/uwp-vs-winui3.html
* https://platform.uno/docs/articles/how-uno-works.html
* https://platform.uno/docs/articles/concepts/overview/philosophy-of-uno.html

**Comment by swharden** [comment]
Note to self, the website needs to be updated to add a WinUI3 quickstart page https://github.com/ScottPlot/ScottPlot.NET/issues/24

**Comment by notofug** [comment]
> @rafntor note that I changed some class names and namespaces to make this control more consistent with the naming of other controls:
> 
> namespace: `ScottPlot.Uno.WinUI` → `ScottPlot.WinUI`
> 
> class: `ScottPlot.Uno.WinUI.UnoPlot` → `ScottPlot.WinUI.WinUIPlot`
> 

I dont mind; I also notice that naming uno packages becomes very confusing in many libraries, and some seem to release multiple packages compiled with different names based on same codebase. I like your thinking, this package is basically a WinUI control, just augmented to also work for uno. As long as it is mentioned in docu and such this makes sense to me too

**Comment by notofug** [comment]
Btw : could you possibly kick a new beta soonish ? We have some ongoing skunk-work that would love that

**Comment by swharden** [comment]
> Btw : could you possibly kick a new beta soonish ? We have some ongoing skunk-work that would love that

Sure thing! I may run out of time to get it done this morning before work, but I can definitely do this at the end of the day 👍 

* #2379

**Pull request merged**
