### PR TITLE
SignalPlotXY: defer ascending X check to ValidateData and only validate between min/max render index

### PR DESCRIPTION
**Pull request by bernhardbreuss**
Hi @swharden,

I have tried to solve #1771 by validating X only between min/max render index.
Doing the check only between min/max render index in the setter didn't worked out very well:
- min/max render index must be set before
- before setting max render index Ys must be set
- min/max render index would have been added to `AddSignalXY` which then already started to look like the obsolete `PlotSignalXY`

Therefore I decided to only use the already present check in `ValidateData`.

### CODE REVIEW

**Comment by bernhardbreuss** [comment]
Hi @swharden, I am afraid but the information in the provided link seems only to work for forks owned by a personal account. However I have added you as a collaborator. Hopefully this way you can also edit the PR branch.

**Comment by swharden** [comment]
> added you as a collaborator

That worked, thanks! I'll make a few changes then merge this in shortly. I recommend not committing new changes on your end while I'm actively working on it 👍 

Thanks again for starting this PR! This will be a great improvement to the library 🚀

**Comment by swharden** [comment]
I reached a good compromise in my last few commits.

* There's now a private flag variable which indicates whether Xs have been validated or not.

* Assigning Xs resets this flag, and the validation isn't performed until Render() is called.

* This gives the user time to assign data and set min/max indexes before validation occurs.

* This strategy also ensures Xs is always checked at least once before the first render, hopefully catching the common user of attempting to plot data with non-ascending X values.

**Comment by bernhardbreuss** [comment]
Hi @swharden, thank you for your hard work. ScottPlot is a great lib, easy and straight forward to use.

**Pull request merged**
