### PR TITLE
Heatmap.FlipHorizontally

### PR DESCRIPTION
**Pull request by Neopentane1**
Update heatmap to be able to flip vertically and horizontally.

### CODE REVIEW

**Comment by Neopentane1** [comment]
First time doing this. Not sure what I did wrong.

**Comment by bukkideme** [comment]
I had the same issue when i did my first PR. You can find a file called autoformat.bat inside the Scottplot project folder, where you did your changes. Run this bat file, then it should fix the project file formatting. Do a commit, then push. 
The autocheck on your PR will run automatically again, and hopefully it will pass the format checking now.

**Comment by swharden** [comment]
> Not sure what I did wrong

[bukkideme](https://github.com/bukkideme) is correct! The project needs to be autoformatted.

```cs
dotnet format
```

I'll go ahead and run the autoformatter now then merge this pull request in. Thanks so much for adding this new feature @Neopentane1! 🚀

**Comment by swharden** [comment]
I updated the cookbook recipe too

```cs
double[,] data = ScottPlot.DataGen.SampleImageData();

var hm1 = plt.AddHeatmap(data, lockScales: false);
hm1.XMin = 0;

var hm2 = plt.AddHeatmap(data, lockScales: false);
hm2.XMin = 100;
hm2.FlipHorizontally = true;

var hm3 = plt.AddHeatmap(data, lockScales: false);
hm3.XMin = 200;
hm3.FlipVertically = true;

var hm4 = plt.AddHeatmap(data, lockScales: false);
hm4.XMin = 300;
hm4.FlipVertically = true;
hm4.FlipHorizontally = true;
```

image

**Pull request merged**
