### PR TITLE
Add legend support to FillY Plottable

### PR DESCRIPTION
**Pull request by msroest**
Closes https://github.com/ScottPlot/ScottPlot/issues/2886

Seems to work as expected:
image

### CODE REVIEW

**Review by msroest — COMMENTED** [review]
Moved to Draft as FillY with no linestyle defined the legend doesn't show properly (it doesn't show the color just the label).  Need to work on it more

**Comment by msroest** [comment]
> Moved to Draft as FillY with no linestyle defined the legend doesn't show properly (it doesn't show the color just the label). Need to work on it more

I've changed the code to ignore the line style and set the legend to the fill color.  I don't love it so I'm open to alternate ideas.

**Comment by swharden** [comment]
Looks like the error is
```
Predefined type 'System.ValueTuple`3' is not defined or imported
```

ScottPlot 5 also targets .NET Framework 4.6.2 so I'm guessing there's a language feature you're using that isn't supported by that framework

https://github.com/ScottPlot/ScottPlot/blob/42987b60b6fb90e94d0fb67a60c7dfafc73d8d9a/src/ScottPlot5/ScottPlot5/ScottPlot.csproj#L4

I can take a closer look when I review this PR later today or tomorrow if it keeps failing unexpectedly build in the cloud. 

Thanks for this contribution, I look forward to merging it in and making it available in the next release! 🚀

**Comment by swharden** [comment]
> Not really sure why it's now trying to compile net462 on linux/macos when it wasn't before (or wasn't failing before)

Actually, don't worry about it!

I just realized the errors are in the color code (unrelated to this PR), so let's keep this PR clean and focused just on FillY, and I'll swoop in and fix the color issues causing the build failure right before I merge 👍 

Thanks again for this PR!

**Pull request merged**
