### PR TITLE
OpenGL: update version line to fix bug causing lines not to be rendered

### PR DESCRIPTION
**Pull request by onur-akaydin**
ScatterGLCustom is not drawing any line due to a small mistake in LinesProgramCustom.cs.

I'm not an expert in OpenGL, but when we write:
"#version 430 core"

instead of:
"# version 430 core"

ScatterGLCustom starts drawing the lines.

### CODE REVIEW

**Comment by onur-akaydin** [comment]
I just noticed that the same mistake exists also in MarkerFillCircleProgram.cs file. Shall I create a new pull request for it?

**Comment by swharden** [comment]
Hi @onur-akaydin, you can make all the changes in this PR.

@StendProg is more familiar with the OpenGL controls so I'll invite their comment if they're free to give feedback on this PR.

Thanks to both of you for your help on this!

**Comment by StendProg** [comment]
Hey @onur-akaydin, @swharden

> I'm not an expert in OpenGL, but when we write:

I'm not an expert either, this project is my only experience.
But you are probably right, you should specify `#version`  
for example according to this http://www.c-jump.com/bcc/common/Talk3/OpenGL/Wk03_shader_intro/W03_0090_glsl_version_number.htm

I have tested, and both work correctly on my machine `# version` and `#version`

Apparently there are different versions of OpenGl drivers, some of them forgive such inaccuracies as I have. Some of them require a more strict specification, like yours.
Let's just fix it as you suggest, it shouldn't be worse.

**Comment by swharden** [comment]
Thanks for your insightful feedback! I'll merge this and push it in the next release later today 👍

**Pull request merged**
