### PR TITLE
Simple 2x2 downsampling method

### PR DESCRIPTION
**Pull request by bukkideme**
Please have a look, not fully tested. Might also require further optimization and better edge case handling.

### CODE REVIEW

**Comment by StendProg** [comment]
Hi @bukkideme,

It can be written down in a simpler and more effective way:
```c#
public static double[,] DownscaleArray(double[,] inputArray)
{
    int height = inputArray.GetLength(0);
    int width = inputArray.GetLength(1);

    int heightNew = (int)Math.Floor((double)height / 2);
    int widthNew = (int)Math.Floor((double)width / 2);

    double[,] outputArray = new double[heightNew, widthNew];

    for (int y = 0; y < heightNew; y++)
    {
        for (int x = 0; x < widthNew; x++)
        {
            double sum = 0;

            // Compute the sum of the values in the 2x2 block
            sum += inputArray[y * 2, x * 2];
            sum += inputArray[y * 2 + 1, x * 2];
            sum += inputArray[y * 2, x * 2 + 1];
            sum += inputArray[y * 2 + 1, x * 2 + 1];

            outputArray[y, x] = sum / 4;
        }
    }

    return outputArray;
}
```

**Comment by bukkideme** [comment]
Cool! Yeah, I tend to create kind of Rube Goldberg codes as first version 😁
This is much simpler now :)

By the way, after you merge this PR with your modifications, can we hope for a new release? :) thanks very much!

**Comment by bukkideme** [comment]
I guess you will create a double?[,] method variation too, where you handle the null elements, when all or some of the 4 elements are null?

**Comment by StendProg** [comment]
> I guess you will create a double?[,] method variation too, where you handle the null elements, when all or some of the 4 elements are null?

I was too lazy to write myself, ChatGPT does a great job:
```c#
public static double?[,] DownscaleArray(double?[,] inputArray)
{
    int height = inputArray.GetLength(0);
    int width = inputArray.GetLength(1);

    int heightNew = height / 2;
    int widthNew = width / 2;

    double?[,] outputArray = new double?[heightNew, widthNew];

    for (int y = 0; y < heightNew; y++)
    {
        for (int x = 0; x < widthNew; x++)
        {
            double sum = 0;
            int count = 0;

            if (inputArray[y * 2, x * 2].HasValue)
            {
                sum += inputArray[y * 2, x * 2].Value;
                count++;
            }
            if (inputArray[y * 2 + 1, x * 2].HasValue)
            {
                sum += inputArray[y * 2 + 1, x * 2].Value;
                count++;
            }
            if (inputArray[y * 2, x * 2 + 1].HasValue)
            {
                sum += inputArray[y * 2, x * 2 + 1].Value;
                count++;
            }
            if (inputArray[y * 2 + 1, x * 2 + 1].HasValue)
            {
                sum += inputArray[y * 2 + 1, x * 2 + 1].Value;
                count++;
            }

            if (count > 0)
            {
                outputArray[y, x] = sum / count;
            }
        }
    }

    return outputArray;
}
```

**Comment by bukkideme** [comment]
> > I guess you will create a double?[,] method variation too, where you handle the null elements, when all or some of the 4 elements are null?
> 
> I was too lazy to write myself, ChatGPT does a great job:
> 
> ```cs
> public static double?[,] DownscaleArray(double?[,] inputArray)
> {
>     int height = inputArray.GetLength(0);
>     int width = inputArray.GetLength(1);
> 
>     int heightNew = height / 2;
>     int widthNew = width / 2;
> 
>     double?[,] outputArray = new double?[heightNew, widthNew];
> 
>     for (int y = 0; y < heightNew; y++)
>     {
>         for (int x = 0; x < widthNew; x++)
>         {
>             double sum = 0;
>             int count = 0;
> 
>             if (inputArray[y * 2, x * 2].HasValue)
>             {
>                 sum += inputArray[y * 2, x * 2].Value;
>                 count++;
>             }
>             if (inputArray[y * 2 + 1, x * 2].HasValue)
>             {
>                 sum += inputArray[y * 2 + 1, x * 2].Value;
>                 count++;
>             }
>             if (inputArray[y * 2, x * 2 + 1].HasValue)
>             {
>                 sum += inputArray[y * 2, x * 2 + 1].Value;
>                 count++;
>             }
>             if (inputArray[y * 2 + 1, x * 2 + 1].HasValue)
>             {
>                 sum += inputArray[y * 2 + 1, x * 2 + 1].Value;
>                 count++;
>             }
> 
>             if (count > 0)
>             {
>                 outputArray[y, x] = sum / count;
>             }
>         }
>     }
> 
>     return outputArray;
> }
> ```

😂 Can you ask ChatGPT to generate for example Lanczos downscaling too? :)

**Comment by StendProg** [comment]
Unfortunately ChatGPT very often cheats, so you need to have a good understanding of what you want, and how you can check the result. I don't understand anything about this method, and I can't check and correct it. But yes, it gives something similar to Lanczos downsampling with a window size of 3

**Comment by swharden** [comment]
Sorry for the delay - I was out of town for a while but I'm back again. Thank you both for your work on this! 

I created a `DataOperations` static class that can be used to house methods like these so they are available to ScottPlot4 and ScottPlot5. I'm going to merge this now, but you are welcome to submit future PRs with additional methods!

**Comment by swharden** [comment]
> welcome to submit future PRs with additional methods!

A method for downscaling by an arbitrary factor (2, 4, 10, etc.) would be a useful tool to have, as many people get stuck trying to display heatmaps with a very large number of data points:

* #2438

**Pull request merged**
