### PR TITLE
Implemented Step Signal Plot

### PR DESCRIPTION
**Pull request by EmanuelFeru**
**Purpose:**
Step Display is very useful to show digital signals. 

**New Functionality:** This PR implements #1092
- added function for `StepDisplay` (take-over from Scatter Plot)
- added Cookbook example
- all tests are passing

image

### CODE REVIEW

**Comment by bclehmann** [comment]
The step plot looks a little weird with dots drawn. I don't know if that's something that can/should be changed. Maybe just changing the demo to not draw marker points is all that should be done?

**Comment by StendProg** [comment]
Hi @EmanuelFeru,

Good improvement, thanks for your contribution.

Unfortunately, SignalXY will inherit `StepDisplays`, but will not react to it in any way. There is no simple solution, I think it is better to leave it as it is for now.

It seems that the `StepDisplay` shows no respect for the existing signal fill above/below. At first glance, it looks easy, it is enough to transfer the already formed array to the code below, but in the process, difficulties may arise. At least it looks like it's worth at least a try. 
What do you think?

> The step plot looks a little weird with dots drawn. I don't know if that's something that can/should be changed. Maybe just changing the demo to not draw marker points is all that should be done?

It also immediately caught my eye, most likely the lack of symmetry gives such an effect.

**Comment by EmanuelFeru** [comment]
Yes, it's the symmetry. I was looking strange at the beginning too 😃 the dots can be hidden by making the Markersize 0. What is your opinion for the example? I can put the Markersize to 0 to have a more natural look.

@StendProg, I did not fully understood. Do you mean it we do surface below for example then it still considers straight line between points?

**Comment by StendProg** [comment]
> @StendProg, I did not fully understood. Do you mean if we do surface below for example then it still considers straight line between points?

Exactly. The fill in the background will connect the dots and will probably be ugly. Maybe we don't need it, but most likely sooner or later this question will come up, it's up to you, I just noticed that the fill uses the old array of points in `stepDisplay` mode.

**Comment by EmanuelFeru** [comment]
I see... Then it's better to have it done now. I will have a look in the next couple of days.

**Comment by EmanuelFeru** [comment]
I quickly checked FillBelow. Indeed it does not draw well around the steps. Still investigating how to make it plot steps. I think a change is needed on the Rectangle fill:
https://github.com/ScottPlot/ScottPlot/blob/3ead8c204116ea95baed60df6715b70cd668beab/src/ScottPlot/Plottable/SignalPlotBase.cs#L428-L432
image

Code for the above plot:
```cs
public void ExecuteRecipe(Plot plt)
{
    double[] ys = DataGen.Sin(51);
    int sampleRate = 1;

    var sig = plt.AddSignal(ys, sampleRate);
    sig.StepDisplay = true;
    sig.MarkerSize = 0;
    sig.FillType = FillType.FillBelow;
    sig.FillColor1 = Color.Blue;

}
```
____
Also I am not sure if the fill is done correctly, it behaves strange when I move and looks diagonal. I would expect to fill similar to here:
https://swharden.com/scottplot/cookbooks/4.1.16/category/plottable-fill/#fill-under-curve
image

**Comment by EmanuelFeru** [comment]
Fixed. I will do a commit.
image

**Comment by EmanuelFeru** [comment]
image

**Comment by swharden** [comment]
Hi @EmanuelFeru, thank you for this PR! Thanks @bclehmann and @StendProg for your input along the way.

I'm going to refine this PR and merge it in shortly despite it not looking perfect with filled signal plots. It looks like filled signal plots have slight rendering errors already, and I'll work to investigate and hopefully fix that in a separate issue (#1163)

**Comment by swharden** [comment]
Thanks @EmanuelFeru, this looks great! This feature will be in the next release 👍🚀 

I'll fix the error affecting the alignment of fills shortly (#1163)

**Pull request merged**
