### PR TITLE
RTL support

### PR DESCRIPTION
**Pull request by StendProg**
Adds support for Right to Left languages. #4306
This change affects the output of absolutely all texts, not just legends as suggested by #4306.

RTL support is disabled by default, and everything works as before, unchanged.
Setting the `LabelStyle.RTLSupport` static property results in additional wrapping of the output text in `Shaper`.
Actually this change may include a lot more than just RTL support, since there's a whole separate engine under the hood for rendering characters, but I'm not good at that.

I really don't like customizing the behavior with a static property, but I don't see any other easy ways to solve this problem. `LabelStyle` constructors are spread all over the project in large numbers.

Added a demo of RTL usage to be displayed in the legend. I'm sure you can fix/extend for better user experience.

```c#
LabelStyle.RTLSupport = true;
var sig1 = myPlot.Add.Signal(Generate.Sin(51));
sig1.LegendText = "אמת";
```

### CODE REVIEW

**Comment by StendProg** [comment]
Perhaps the pipeline error is related to this flag:

dotnet test "src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj" --configuration Release ***--no-build*** --verbosity minimal

**Comment by swharden** [comment]
I'll remove the `--no-build` flag and if that doesn't work I'll try adding HarfBuzz as a dependency in the Cookbook project. I think the act of installing it as a NuGet package in a project ensures the DLLs it requires get copied to the correct place. We'll see 🤞

**Comment by swharden** [comment]
... nope, that didn't work. I'm now suspecting the build only fails on Linux systems.

**Comment by swharden** [comment]
That worked! For others having a similar issue running an app that depends on SkiaSharp.HarfBuzz on a Linux system:

```
System.DllNotFoundException : Unable to load shared library 'libHarfBuzzSharp' or one of its dependencies. 
```

I solved it by adding the following to my csproj:
```xml
<PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="7.3.0.3" />
```

**Pull request merged**
