### PR TITLE
Improve descriptive statistics class

### PR DESCRIPTION
**Pull request by arthurits**
**Purpose:**
* Implements #3055.
* Input parameters are defined as `IEnumerable<T>` instead of `double`.
* Uses `IEnumerable<T>.Average()` to compute the data average.
* Functions `StDev` are renamed to `StdDev`.
* Code for `StdDev` is modified:
  * Booleand parameter `asSample` is added to compute both the population and the sample standard deviations.
  * Code checks for and avoids division by 0 runtime exceptions.
  * Function is overloaded with respect to parameter `mean`.
* Function `StdErr` (standard error of the mean) is added.

### CODE REVIEW

**Comment by swharden** [comment]
Hi @arthurits, thanks so much for this PR! This is fantastic, and I look forward to merging it in a few minutes!

> Functions StDev are renamed to StdDev.

Note that I'll keep it `StDev` to be consistent with naming I typically find in Python data analysis packages. I try to mimic the API of those packages (especially matplotlib) where possible
* https://docs.python.org/3/library/statistics.html#statistics.stdev
* https://numpy.org/doc/stable/reference/generated/numpy.std.html

**Comment by swharden** [comment]
Thinking out loud about performance...

I'm tempted to make this an `IReadOnlyList` which will allow it to accept both `List<double>` and `double[]` and I think offer improved performance because `.Count` can be used instead of Linq's `.Count()` ... Probably the decision should be made with proper benchmarks to prove it's meaningfully faster, but I'm not really motivated to micro-optimize these methods at this time.

Similarly, I'll probably make the overloads private that accept the `mean` "for performance". Maybe it saves a few cycles by not calculating mean twice, but calculating mean isn't very costly considering that function is loaded with `Sqrt()` calls which are a lot more significant

**Comment by swharden** [comment]
One more thought, rather than passing a flag to switch between population or sample standard deviation, I'll probably make it two functions to mimic python
* https://docs.python.org/3/library/statistics.html#statistics.stdev
* https://docs.python.org/3/library/statistics.html#statistics.pstdev

**Comment by swharden** [comment]
[sorry about the message bomb here lol] ... thinking _more_ out loud,

In researching Microsoft's naming of this stuff, it looks like they favor `StandardDeviation()` and `StandardDeviationP()` which is a few more keystrokes but may be more readable be a better reference than Python APIs

* https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.core.objects.entityfunctions.standarddeviation?view=entity-framework-6.2.0
* https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.core.objects.entityfunctions.standarddeviationp?view=entity-framework-6.2.0

**Comment by swharden** [comment]
> I look forward to merging it in a few minutes!

A few minutes turned into a few hours - what a rabbit hole! I think this ended in a fantastic place though and I'm merging now. Thanks again for your help getting this started @arthurits! 

There's room for benchmark-driven micro-optimization in the future, but I'm happy where this is.

**Comment by arthurits** [comment]
Hi @swharden. Although it looked quite straightforward, it turns out there were many points to address.
The final code looks great!

**Pull request merged**
