### PR TITLE
Pie chart: add support for "donut" display style

### PR DESCRIPTION
**Pull request by aespitia**
#3438

this is to add the donut functionality that was in SP4 and port to SP5.

### CODE REVIEW

**Comment by aespitia** [comment]
would love feedback on this @swharden, my first time messing with the actual rendering code, so I wouldn't be surprised if there's another/better way to do this.

**Comment by swharden** [comment]
Thanks so much for this @aespitia! 

I'm going to modify this PR slightly to draw the outline around the inner donut, then merge 🚀 

image

**Comment by swharden** [comment]
> draw the outline around the inner donut

Oof, this got complicated fast 😱 It means we need to use a path and "ArcTo" instead of the clever clipping method 🤦 

I'm going to merge this now and create a new issue to track that refinement. If you want to have a go at it, awesome! If not, that's okay too - someone from the community may get to it. If not, I'll implement it eventually 😎

**Comment by swharden** [comment]
Got it! That was actually super confusing 🤪 

image

**Comment by aespitia** [comment]
awesome, thanks so much!

**Pull request merged**
