### PR TITLE
Support Avalonia 11.0.0 preview2

### PR DESCRIPTION
**Pull request by Xerxes004**
**Purpose:**
- Updates AvaPlot and demo to use Avalonia 11.0.0-preview2
- Fixes event names breaking changes
- Uses `IStorageProvider` for save dialog

**See also:**
- https://github.com/ScottPlot/ScottPlot/issues/2183
- https://github.com/AvaloniaUI/Avalonia/discussions/9004

### CODE REVIEW

**Comment by Xerxes004** [comment]
@swharden 

A note about `IStorageProvider`: The provider favors streams over filenames, probably in an effort to make the API completely agnostic to file path strings. It would be a good idea, in my opinion, to have a `SaveFigure` overload that took a stream instead of a filename to support this. Currently, I just use `Uri` to get the path.

**Comment by Xerxes004** [comment]
I also just ran into a pretty major bug with `System.Drawing.Common`. It has to do with [this breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). Microsoft has decided to offload the cross-platform work onto Skia and MAUI implementations, rather than support this "subpar" option.

On my M1 Mac I had to add the recommended *`runtimeconfig.template.json`* file with the following contents:

```json
{
   "configProperties": {
      "System.Drawing.EnableUnixSupport": true
   }
}
```

I added this file to the root of my own project which references ScottPlot. The plot shows up just fine.

I'm looking forward to ScottPlot 5!

**Comment by Xerxes004** [comment]
For anyone who finds this PR, the error I received was:

```
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
```

**Comment by swharden** [comment]
HI @Xerxes004, sorry it took so long for me to properly address this.

We had a quick chat in the Discord #1966 and decided that ScottPlot's controls should only target Avalonia releases (not previews). I'll close this PR for now, but when Avalonia 11 is fully released we can open it up again and pick this up from there 👍

**Comment by bclehmann** [comment]
I think another good alternative is merging this into a separate branch, which we can rebase or fix up whenever Avalonia 11 becomes stable.

**Comment by Xerxes004** [comment]
Hey @swharden @bclehmann no problems, I totally understand. For now I'm going to target released Avalonia in a separate project and just use that separately from our main project.

**Pull request closed without merging**
