### PR TITLE
Bump Avalonia versions to 0.10.2

### PR DESCRIPTION
**Pull request by bclehmann**
**New Contributors:**
please review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)

**Purpose:**
Avalonia versions go from 0.10.0 -> 0.10.2

(0.10.1 does exist but they released a new version a few hours later to undeprecate something: https://github.com/AvaloniaUI/Avalonia/discussions/5820)

**New Functionality:**
N/A

### CODE REVIEW

**Comment by bclehmann** [comment]
As an aside, the 4.0 branch still depends on Avalonia 0.9.11 even though 0.10.0 has been out a while (released December 29, 2020). This prevents anyone from using a stable version of ScottPlot with Avalonia 0.10. Seeing as we already have a couple things to backport this may be a wise addition.

The changes that had to be made to allow Avalonia 0.10.0 on the 4.1 betas are listed here: https://github.com/ScottPlot/ScottPlot/issues/571 https://github.com/ScottPlot/ScottPlot/pull/656

**Comment by bclehmann** [comment]
0.10.3 has come out as well

**Comment by swharden** [comment]
Hey @bclehmann, sorry for the delay here. I'm back now and hope to put some more time into this library over the next few days.

> 0.10.3 has come out as well

Does this mean 3 files in this PR should all be bumped again, or are the changes required more substantial? 

I'll go ahead and merge this and try to get ScottPlot out of pre-release this weekend 🤞

**Comment by bclehmann** [comment]
Yes, they should all be bumped again. Sorry for the slow response.

**Pull request merged**
