### PR TITLE
ScottPlot 5: Basic pie chart

### PR DESCRIPTION
**Pull request by bclehmann**
image

```cs
WpfPlot.Plot.AddPie(new PieSlice[]
{
    new() { Value = 6, Fill = new() { Color = Colors.Red } },
    new() { Value = 4, Fill = new() { Color = Colors.Blue } },
    new() { Value = 3, Fill = new() { Color = Colors.Green } },
    new() { Value = 1, Fill = new() { Color = Colors.DarkCyan } },
});
```

### CODE REVIEW

**Comment by bclehmann** [comment]
The things in the API that felt I was missing (that I haven't added) were the following:
- `axis.PxPerUnit`, I used some `GetPixel` math instead because I don't know how you want that to look
- `GetNextColor`, I wanted to have a `Plot.AddPie(IList<double> values)`, but picking the next colour isn't there yet
- `HatchStyle`, this is a fair bit of work in SkiaSharp it seems
- Legends. Pie charts are a little annoying to label so I was tempted to just dump it in a legend, but those don't exist yet

**Comment by bclehmann** [comment]
I also went back and forth on moving axis validation and clipping code into `PlottableBase.Render` but decided against it because not all plottables actually rely on their axes (such as `DebugBenchmark`). Perhaps it's worth distinguishing between plottables and renderables?

**Comment by swharden** [comment]
```cs
Plottables.PieSlice[] slices =
{
    new(6, Colors.Red),
    new(4, Colors.Blue),
    new(3, Colors.Green),
    new(1, Colors.DarkCyan),
};

plt.AddPie(slices);
```

image

**Comment by swharden** [comment]
> PxPerUnit

> axis validation and clipping code

Let's put these topics down for now but pick them up later. 

I'm going to to start working a lot on the render loop, so this is in flux.

> GetNextColor

#2009 will help here 🚀

**Pull request merged**
