### PR TITLE
Adds "Open in New Window" to context menus

### PR DESCRIPTION
**Pull request by bclehmann**
**New Contributors:**
please review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)

**Purpose:**
#958 #716 

**New Functionality:**
image

### CODE REVIEW

**Comment by bclehmann** [comment]
I believe I have discovered why I have had issues recently with `dotnet format`, I had version 4.1.131201 installed and Azure Pipelines uses the most recent (5.0.211103). I assume there's some subtle difference between the two.

**Comment by swharden** [comment]
Thanks @bclehmann, you beat me to this! I tried to reduce some of the complexity in the WpfPlot control by simplifying construction of the menu, but if there's something I'm overlooking using this strategy let me know.

>  issues recently with dotnet format

Apparently .NET 5 formats things a little differently than .NET 4 🙄

You probably figured this out, but the latest way to update the formatter and run it is:
```
dotnet tool update -g dotnet-format
dotnet format
```

**Comment by bclehmann** [comment]
> I tried to reduce some of the complexity in the WpfPlot control by simplifying construction of the menu, but if there's something I'm overlooking using this strategy let me know.

I made it so that it would only create the default context menu once, and just keep reusing the same thing after that. I admit the code is not as clear, and the performance difference is likely minuscule. Depending on how you feel you can more or less just copy-paste the code over to Avalonia, I think the only changes you need to make is to replace `IsOpen = true` with `Open(this)`, and then comment out the copy image stuff because Avalonia doesn't offer an easy way to add photos to the clipboard.

**Comment by swharden** [comment]
> the code is not as clear, and the performance difference is likely minuscule

Okay cool - that's what I thought, but I just wanted to double check. My goal is to keep the WinForms and WPF controls as simple and easy to read as possible, since common advice I give to people asking for advanced features is "make your own control based on the existing one - it's only a couple hundred lines". Those programmers may not be that experienced with C#, so I try extra hard to keep those two modules as minimalistic and easy to read as possible

> Depending on how you feel you can more or less just copy-paste the code over to Avalonia

I'm less worried about the Avalonia control code because I assume Avalonia users are stronger programmers 🙃

Thanks again for your quick work on this! The PR came in just in time to include it in tonight's release on NuGet 🚀

**Pull request merged**
