### PR TITLE
PlotStyle: styling information that simplifies storing, recalling, and copying plot styles

### PR DESCRIPTION
**Pull request by StendProg**
This PR adds the `Plot.Style.IsDarkMode` property.
This property allows you to toggle the display mode light/dark. If the user has changed any colors manually, these colors are not affected by the switch and remain as configured by the user.
Calling the `Plot.Style.GrabLightSettings()` method allows you to save the changes made by the user as light theme settings.

`IsDarkMode` is not a good name for the set value property. The more appropriate `DarkMode` is already taken up by the `DarkMode()` method. Renaming it would be a breaking change.

```cs
    private void DarkModeCheckBox_CheckedChanged(object sender, EventArgs e)
    {
        formsPlot1.Plot.Style.IsDarkMode = DarkModeCheckBox.Checked;
        formsPlot1.Refresh();
    }
```

https://github.com/ScottPlot/ScottPlot/assets/53831487/36a0bce2-04c8-4932-bceb-9e8cb2f5ee7e

### CODE REVIEW

**Comment by swharden** [comment]
Hi @StendProg, thanks so much for this PR! The timing is great as I was about to start working on #3955

I may refactor this a bit before merging it in, but I'll have it merged before the next release for sure.

I look forward to reviewing this! 🚀

**Comment by heartacker** [comment]
great~

**Comment by swharden** [comment]
I think I've recreated the original behavior... customized style settings can be recognized and preserved even as new styles are applied. I'll probably put this down for tonight and pick it up again tomorrow, but I'm encouraged by the direction that this is going 😄 

image

image

```cs
public Form1()
{
    InitializeComponent();

    var sig1 = formsPlot1.Plot.Add.Signal(Generate.Sin());
    sig1.LegendText = "Sin";
    var sig2 = formsPlot1.Plot.Add.Signal(Generate.Cos());
    sig2.LegendText = "Cos";

    // apply custom styling options
    formsPlot1.Plot.Legend.BackgroundColor = Colors.Magenta;
    formsPlot1.Plot.Legend.FontColor = Colors.White;

    // prepare the two styles we will be switching between later
    PlotStyle lightStyle = new ScottPlot.PlotStyles.Light();

    // the WinForms control customizes light style by setting background to match the form
    lightStyle.FigureBackground = ScottPlot.Color.FromColor(SystemColors.Control);

    PlotStyle darkStyle = new ScottPlot.PlotStyles.Dark();
    PlotStyle customStyle = formsPlot1.Plot.GetStyle().WhereDifferentFrom(lightStyle);

    checkBox1.CheckedChanged += (s, e) =>
    {
        // apply light or dark mode
        if (checkBox1.Checked)
            formsPlot1.Plot.SetStyle(darkStyle);
        else
            formsPlot1.Plot.SetStyle(lightStyle);

        // apply the customized style options
        formsPlot1.Plot.SetStyle(customStyle);

        formsPlot1.Refresh();
    };
}
```

**Comment by kebox7** [comment]
Hi @swharden. This PR is already closed, but I have some comments/suggestions.

https://github.com/ScottPlot/ScottPlot/blob/723f18744c52460a60072f6cbfc61093153b292d/src/ScottPlot5/ScottPlot5/Primitives/PlotStyle.cs#L12-L13

For consistency, change `DataBackGround` to `DataBackground`.

https://github.com/ScottPlot/ScottPlot/blob/723f18744c52460a60072f6cbfc61093153b292d/src/ScottPlot5/ScottPlot5/Primitives/PlotStyle.cs#L20-L21

`LegendFont` is more associated with the font name, but not the color. It might be better to change it to `LegendForeground` or `LegendText`.

**Comment by swharden** [comment]
Good point @kebox7, thanks for pointing that out! I meant to rename all those properties but I forgot to before merging... I opened #4036 to track the fix and added my recommended names there. If you get to it before I do and create a pull request, I'd be happy to merge it in! Otherwise I'll pick it up next time I work on this project 👍

**Pull request merged**
