### PR TITLE
Fix - Support for draggable plottables on `AxisIndex` 0 and 1

### PR DESCRIPTION
**Pull request by BambOoxX**
- Former behavior only worked for `AxisIndex` 0

This PR is related to the discussion on #1545 

There is still work to generalize this to other axis indexes, but I don't know to reach other axes at the moment.

### CODE REVIEW

**Comment by swharden** [comment]
FYI, I added some draggable lines to the multi-axis lock WinForms demo in this PR branch to facilitate testing...

Demo Menu | Screenshot
---|---
image|image

**Comment by swharden** [comment]
I have to put this down for tonight but I can pick it up in the morning. It's _really_ close to working properly now, but the horizontal line on third axis still isn't properly draggable. I think it's because its snap height is being calculated improperly 🤔 

If you figure it out before I get to it next, feel free to commit a fix! Otherwise I'll pick it up in the morning 👍

**Comment by BambOoxX** [comment]
> I have to put this down for tonight but I can pick it up in the morning. It's _really_ close to working properly now, but the horizontal line on third axis still isn't properly draggable. I think it's because its snap height is being calculated improperly 🤔

It's funny, I feel its working properly on my side. Can you elaborate the wrong behavior ?

**Comment by BambOoxX** [comment]
@swharden just fixed the snapped distance.

**Comment by swharden** [comment]
> @swharden just fixed the snapped distance

I stared at that for a while last night but I didn't realize what I was doing wrong until I saw 03c5771e4e56a7b58beba374e52a7f0e265cffa6 - axes should be pulled from the plottable, not passed in as arguments - great catch!

Thanks so much for your work on this PR! 👍 🚀

**Pull request merged**
