### PR TITLE
#4135 Heatmap keeps crashing with live data feed

### PR DESCRIPTION
**Pull request by MahmoudArabied**
Added thread locker to ensure a thread-safe operation of accessing bitmap object

### CODE REVIEW

**Comment by bforlgreen** [comment]
It is the responsibly of the calling code (i.e your code) to manage threading.

More info here
https://scottplot.net/faq/async/

**Comment by MahmoudArabied** [comment]
@bforlgreen Thank you for your feedback. It is understandable that I've to be manage threading in my code. I'm sorry I couldn't share any kind of source code sample from my side.  I described the issue within this ticket https://github.com/ScottPlot/ScottPlot/issues/4135

Dealing with bitmap objects within protect memory is very critical. In my case, my source code generates the heatmap every 100msec, this might lead to memory corrupted issue if the object is updated, deleted or being accessed from another thread/class even if the access within the same thread! However, I don't know what exactly occur in SkiaSharp.dll.

In the example you shared under this page
https://scottplot.net/faq/async/

In my opinion it is a risky operation to include a waiting while loop without timeout! What will happen if there is an internal error within "IsRendering", dealing with UI, this could lead to an unresponsive UI or even in worse case a crash.

What I shared in my 'Pull Request' is to include a thread lock, this is very safe in C# as the thread pool will manage the thread access and release it once the operation is completed. It does not have any performance issue. Using this approach, I couldn't reproduce the issue of  'System.AccessViolationException'  anymore.

**Comment by bforlgreen** [comment]
@MahmoudArabied these are just some of my thoughts, Scott might disagree, I am not sure what his intentions for threading are. So he might have other thoughts.

The problem is that you have a added a lock that only works in your specific scenario and for only one plot type. There are many other cases just in that one `HeatMap` class where it could still break. Aside from the inconsistency with other plots, its now not clear (or documented) which parts are actually thread-safe.

The other problem is that locking does incur a performance penalty. So if you were to add it to all the necessary places in all plot types, it would most certainly have some impact on performance, probably only very small, but it would be there. It also makes development much harder, as now you need to consider all the potential places state could be updated from another thread. So maintenance is more involved.

It's simply much easier for users of the library to stop rendering, perform their update, and then continue rendering. I am not sure why you mention you would need a timeout. You'll only be waiting for the the last render to complete. As for blocking the UI, this is no different to your lock in the render.

The PreRenderLock might be a more suitable place for you also. Which is even easier to use.

The benefits of both these options is that you're only *optionally* locking once per frame. Not in a million places all over the code base. So it's the best of both worlds really.

Again, just my opinion.

**Comment by swharden** [comment]
Hi @MahmoudArabied and @bforlgreen, thanks for this PR and useful discussion! 

While there's nothing wrong with the implementation put forth in this PR, it is true that "modifying data while rendering" can be a problem that affects many plot types, but this fix only adds a solution for heatmaps.

Based on this PR and discussion I clarified the recommended strategy for updating data in a way that won't cause unexpected behavior when rendering https://github.com/ScottPlot/ScottPlot/issues/4135#issuecomment-2309004190

If the strategy there isn't sufficient to meet your needs, let me know and we can take a closer look and figure out a better solution! 

Thanks again for both of your input along the way 👍

**Comment by swharden** [comment]
Recognizing ScottPlot 4's API seems to be much simpler than ScottPlot 5, I created an issue #4174 aimed at making the recommended locking strategy more discoverable. I welcome suggestions!

**Comment by MahmoudArabied** [comment]
@swharden @bforlgreen I really appreciate your input on this issue. Engaging in meaningful discussions can help clarify the ideas behind multithreading and locking. I find the way you introduced thread locking is clear and easy to implement. I will follow the issue in https://github.com/ScottPlot/ScottPlot/issues/4174.

**Pull request closed without merging**
