### PR TITLE
Avalonia 0.10.0

### PR DESCRIPTION
**Pull request by Benny121221**
**New Contributors:**
please review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)

**Purpose:**
Adds support for Avalonia 0.10.0rc1. #571

**New Functionality:**
Works correctly on the latest Avalonia Release Candidate.

I created this pull request in anticipation of an imminent non-prerelease version of Avalonia. In theory, all one would have to do is change the package references to the new version. I said earlier that I would do this once it had actually been released, however, I currently have finals and I would like to have the actual work done in advance (turned out there wasn't much work to do anyways) so I can focus on those. So even if the new version drops right in the middle of finals no one would have to wait for support on the latest version. I'm not expecting any breaking changes between now and the release of 0.10.0, so it *should* just be as simple as changing the package versions.

Also, the Avalonia cookbooks do not work, I believe this is from #639, not anything specific to the new Avalonia version. I have elected not to touch the cookbooks at all for this reason. I did touch one demo because there was a minor change to the `PlotViewer` class in e182ae3.

### CODE REVIEW

**Comment by Benny121221** [comment]
When the new release drops I can change the package references in `ScottPlot.Avalonia.csproj` and `Avalonia Demo.csproj` and assuming there are no problems I will mark it as not a draft PR.

**Comment by swharden** [comment]
Hey @Benny121221, I recognize a lot of the code base is pretty active right now, but thanks for working around it and issuing this PR!

> Also, the Avalonia cookbooks do not work, I believe this is from #639

They seem to be working on the latest version of the master branch... but this is probably a separate topic we can explore deeper as we get closer to a release.

image

> I currently have finals and I would like to have the actual work done in advance (turned out there wasn't much work to do anyways) so I can focus on those

I really appreciate all the work you've put in to make this library better! Take all the time you need to ensure you'll do great on those finals, and fingers crossed I'll continue to have made good progress between now and then 🤞

**Comment by Benny121221** [comment]
> They seem to be working on the latest version of the master branch... but this is probably a separate topic we can explore deeper as we get closer to a release.

Yeah, you are correct. I just saw `NullReferenceException` on the template tree and assumed that you changed its structure without reading deeper. Turns out it's an issue where `TreeView.SelectedItem` can be null even when there is a selection. I fixed this by using `TreeView.SelectedItems` (a list).

@FoggyFinder knows more about Avalonia than me, this isn't listed anywhere in the [breaking changes ](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#09---010).

There are similar issues listed in this gitter: https://gitter.im/AvaloniaUI/Avalonia?at=5e479a1fd56ddb68a4a79fcd

My observed behaviour was clicking the first time would set `SelectedItem` to null, and the second click would set it to the expected value. If I'm doing something wrong I would be happy to open an issue in the Avalonia repo.

**Comment by Benny121221** [comment]
@swharden Avaloniao 0.10.0 was released earlier this morning. I have rebased this branch to match up with master.

**Comment by swharden** [comment]
> @swharden Avaloniao 0.10.0 was released earlier this morning. I have rebased this branch to match up with master.

Awesome, is this ready to merge now?

I plan to make another beta release on NuGet this weekend so this can get out there in the wild pretty soon!

**Comment by swharden** [comment]
> is this ready to merge now?

I'm pretty sure it is and you're done with this PR, so I'll save you the reply an go ahead and merge, then I can start working on #700 👍

**Pull request merged**
