### PR TITLE
Creates errorbar plottable and cookbook

### PR DESCRIPTION
**Pull request by bclehmann**
**New Contributors:**
Please review [CONTRIBUTING.md](https://github.com/swharden/ScottPlot/blob/master/CONTRIBUTING.md)

**Hacktoberfest Participants:**
Check-out the [Hacktoberfest 2021](https://github.com/ScottPlot/ScottPlot/issues/1274) page

**Purpose:**
#1466
image

### CODE REVIEW

**Comment by bclehmann** [comment]
For what it's worth, it's been a while since I've made a PR that touched rendering (I think it was #1188...) and I have to say that things like `Coordinate` and `Pixel` seem like a nice common-sense addition. I remember a lot of tuple-wrangling before.

It might even be possible to claw back some performance by converting them to structs since they're small and potentially could be allocated every render.

**Comment by swharden** [comment]
> things like Coordinate and Pixel seem like a nice common-sense addition

Thanks! I made them because I kept confusing myself passing `(double x, double y)` 😝 

> It might even be possible to claw back some performance by converting them to structs since they're small and potentially could be allocated every render

If I'm going to refactor ScottPlot 4, it'll probably be to favor readability and portability over performance. Switching to Maui.Graphics will be a pretty big shake-up, so it may not be worth optimizing ScottPlot 4 at this time.

BTW you might get a kick out of #1561 - It's barebones but the WinForms app is the most developed. I'm experimenting with architecture. After a few years getting to know the pain points of this library, I'm leaning toward minimizing state stored in the plot module itself. Types like `AxisLimits`, `Pixel`, and `Coordinate` are structs with a fluent interface. I don't intend to greatly change the public API (the plot methods will be essentially the same), but I'm starting to like things like this...

```cs
PlotView mouseDownView = plt.GetAxisLimits();
PlotView currentView = mouseDownLimits.WithPan(mouseDownPixel, mouseNowPixel);
Bitmap bmp = plt.Render(currentView);
```

None of this is set in stone (I'm still waiting for Maui.Graphics to mature - it's getting there though), but it's interesting to consider after working with this library and having a good understanding of its roughest edges.

**Comment by swharden** [comment]
Great work as always @bclehmann, thanks so much for this PR! I'll merge this now and release this weekend.

~~This could even be extended in the future~~ by adding a `MarkerShape` and `MarkerSize` to allow people to make plots like this (although I'd probably use the same color for the error lines and the marker)

_EDIT: I'll put this in now real quick, then merge_

image

**Comment by bclehmann** [comment]
Sorry, I found this after you merged, but there's a bug in the error bar rendering code. They can be drawn outside the plotting frame.

image

**Comment by swharden** [comment]
> Sorry, I found this after you merged

No worries! It'll be a few hours before I publish the next package, so this fix will make it in

> I'm confused why this happens, because I don't think the other plottables check for points outside the frame, but they don't seem to suffer from this problem

My trick is to avoid calling `Graphics.FromImage(bmp)` and instead I call an internal method which clips the data area according to the `PlotDimensions` - here's the fix https://github.com/ScottPlot/ScottPlot/commit/6bb43a30e294227ef4954c96abe5be0f8bf44841

**Pull request merged**
