### PR TITLE
Triangular Axis

### PR DESCRIPTION
**Pull request by manaruto**
Summary

This pull request introduces a new TernaryAxis class to support ternary plot capabilities within ScottPlot. It also includes two helper classes, TernaryAxisCornerLabel and TernaryAxisEdge, which allow for more customizable and flexible ternary plots.
Changes Introduced

    TernaryAxis Class:
        Provides the core functionality for creating and rendering ternary plots.
        Includes options for customizable ticks, grid lines, background color, and minor grid settings.

    TernaryAxisCornerLabel Class:
        Allows customization of corner labels, including text size, color, offset, alignment, and bolding options.

    TernaryAxisEdge Class:
        Defines edges of the ternary triangle and enables customizable line styles, including color, thickness, and alpha (transparency).

Usage Example

```
var myPlot = new ScottPlot.Plot();
var ternaryAxis = new TernaryAxis();

// Customize corner labels
var componentALabel = ternaryAxis.CornerLabels[0];
componentALabel.LabelText = "Fuel (Methane)";
componentALabel.TextSize = 14;
componentALabel.Color = ScottPlot.Colors.Red;
componentALabel.IsBold = true;

// Add the ternary axis to the plot
myPlot.Add(ternaryAxis);
myPlot.SavePng("ternary_plot.png");
```

Issue Reference

This PR addresses and implements new ternary plotting features [#4413](https://github.com/ScottPlot/ScottPlot/issues/4413)

### CODE REVIEW

**Comment by swharden** [comment]
Hi @manaruto, wow that was super fast! 🚀 

I'll probably be able to review this tomorrow and merge it in, then release it in the next NuGet package Sunday.

Note that the build is failing here because in pull requests it treats warnings as errors, so if you're able to resolve the warnings that would be helpful.

Thanks again!
Scott

**Comment by manaruto** [comment]
I’ve addressed all the warnings and fixed the issues, so the build should pass now. Let me know if there's anything else you’d like me to adjust.

Thanks for the guidance!

**Comment by swharden** [comment]
Hi @manaruto, thanks again for this! I'm going to refine this a bit and make commits directly into this branch, so I recommend not making additional changes here because it may lead to merge conflicts. If you have additional suggestions after my changes, we can open up new pull requests to refine it based on your suggestions. I'm excited to merge this in soon!

**Comment by swharden** [comment]
Note that I'm going to rename `TernaryAxis` to `TriangularAxis` because my understanding is that ternary plots are for displaying points that must add to 100%, but a triangular axis is more flexible. Users could use a triangular axis to display ternary data if they want, but keeping it "triangular" makes it a little more flexible for other use cases.

**Comment by swharden** [comment]
Making progress! 

Wow this is more complicated than I thought though. Classic problem for all programmers 🙃 

image

**Comment by swharden** [comment]
Just finished adding cookbook examples and am about to merge this in. This is looking fantastic! 🚀 

```cs
var ta = myPlot.Add.TriangularAxis();

ta.Bottom.Title("Methane", Colors.Red);
ta.Left.Title("Nitrogen", Colors.Green);
ta.Right.Title("Oxygen", Colors.Blue);

Coordinates[] points = [
    ta.GetCoordinates(0.50, 0.80, 0.20),
    ta.GetCoordinates(0.50, 0.60, 0.40),
    ta.GetCoordinates(0.65, 0.70, 0.30),
    ta.GetCoordinates(0.80, 0.80, 0.20),
];

myPlot.Add.Markers(points, MarkerShape.FilledCircle, 10, Colors.Red);
```

image

**Comment by swharden** [comment]
Hi @manaruto, I'd like your input on this. Should the units on the bottom extend from left to right or right to left? It seems they're not consistent in the screenshots shown in #4413

left to right | right to left
---|---
image|image

**Comment by manaruto** [comment]
Typically, clockwise is more commonly used in general applications, but some ternary plots use counterclockwise labeling for geological applications, which is my field, so it will be good if we make an option for both settings, thanks.

**Comment by swharden** [comment]
> Typically, clockwise is more commonly used in general applications, but some ternary plots use counterclockwise labeling for geological applications, which is my field, so it will be good if we make an option for both settings, thanks.

Done! `Add.TriangularAxis()` now has an optional argument to toggle clockwise vs. counter-clockwise (#4424)

**Pull request merged**
