### PR TITLE
Heatmap: support additional flipping options

### PR DESCRIPTION
**Pull request by BrianAtZetica**
This addresses the suggestions in #3418.

Heatmaps can now be flipped in rows or columns, which is tooling designed to be data-centric (i.e. controlling how the data are arranged in the array irrespective of how they are eventually plotted).
Note that flipping is no longer referred to as FlipVertically, so this will be a breaking change for some code.

This is complemented by the ability to flip the image relative to the coordinate axes using the Extent property.

Flipping vertically and horizontally by both methods are demonstrated by the following code:

```cs
        double[,] data = SampleData.MonaLisa();
        var hm1 = WpfPlot1.Plot.Add.Heatmap(data);

        // MonaLisa is sized 65 x 100 pixels.
        hm1.Extent = new(0, 64, 0, 99);
        hm1.FlipRows = false;
        hm1.FlipColumns = false;
        WpfPlot1.Plot.Axes.SetLimits(-1, 65, -1, 100);
        WpfPlot1.Plot.Title("Default Image Orientation");
        hm1.Smooth = true;
        WpfPlot1.Plot.SavePng("MonaLisaNormal.png", 650, 1000);

        hm1.Extent = new(0, 64, 99, 0);
        hm1.FlipRows = false;
        hm1.FlipColumns = false;
        WpfPlot1.Plot.Axes.SetLimits(-1, 65, -1, 100);
        WpfPlot1.Plot.Title("Image Flipped Vertically using Extent");
        WpfPlot1.Plot.SavePng("MonaLisaInvertedY1.png", 650, 1000);

        hm1.Extent = new(0, 64, 0, 99);
        hm1.FlipRows = true;
        hm1.FlipColumns = false;
        WpfPlot1.Plot.Axes.SetLimits(-1, 65, -1, 100);
        WpfPlot1.Plot.Title("Image Flipped Vertically using FlipRows");
        WpfPlot1.Plot.SavePng("MonaLisaInvertedY2.png", 650, 1000);

        hm1.Extent = new(64, 0, 0, 99);
        hm1.FlipRows = false;
        hm1.FlipColumns = false;
        WpfPlot1.Plot.Axes.SetLimits(-1, 65, -1, 100);
        WpfPlot1.Plot.Title("Image Flipped Horizontally using Extent");
        WpfPlot1.Plot.SavePng("MonaLisaInvertedX1.png", 650, 1000);

        hm1.Extent = new(0, 64, 0, 99);
        hm1.FlipRows = false;
        hm1.FlipColumns = true;
        WpfPlot1.Plot.Axes.SetLimits(-1, 65, -1, 100);
        WpfPlot1.Plot.Title("Image Flipped Horizontally using FlipColumns");
        WpfPlot1.Plot.SavePng("MonaLisaInvertedX2.png", 650, 1000);

```

MonaLisaInvertedX1
MonaLisaInvertedX2
MonaLisaInvertedY1
MonaLisaInvertedY2

### CODE REVIEW

**Comment by BrianAtZetica** [comment]
Found a better solution to #3418 that doesn't involve changes to the CoordinateRect class. 
Also provided a fix for #3434, which was tested for all four flips descriebd above and for multiple CellAlignments.

Code for testing:

`

        double[,] data = { { 1, 2 }, { 3, 4 }, { 5, 6 } };
        var hm1 = WpfPlot1.Plot.Add.Heatmap(data);
        hm1.CellAlignment = Alignment.MiddleCenter;
        // User defines an X extent of 0 to 1 (intending the first column on 0 and the second column on 1).
        // User defines an Y extent of 0 to 2 (intending the first row on 0 and last row on 2).
        hm1.Extent = new(0, 1, 0, 2);
        hm1.FlipRows = false;
        hm1.FlipColumns = false;
        WpfPlot1.Plot.Axes.SetLimits(-1.2, 2.2, -1.2, 3.2);
        WpfPlot1.Plot.Title("Default Image Orientation");
        hm1.Smooth = false;
        WpfPlot1.Plot.SavePng("2x3 grid Default.png", 300, 400);

        hm1.Extent = new(0, 1, 2, 0);
        hm1.FlipRows = false;
        hm1.FlipColumns = false;
        WpfPlot1.Plot.Axes.SetLimits(-1.2, 2.2, -1.2, 3.2);
        WpfPlot1.Plot.Title("Flipped Vertically (Extent)");
        WpfPlot1.Plot.SavePng("2x3InvertedY1.png", 300, 400);

        hm1.Extent = new(0, 1, 0, 2);
        hm1.FlipRows = true;
        hm1.FlipColumns = false;
        WpfPlot1.Plot.Axes.SetLimits(-1.2, 2.2, -1.2, 3.2);
        WpfPlot1.Plot.Title("Flipped Vertically (FlipRows)");
        WpfPlot1.Plot.SavePng("2x3InvertedY2.png", 300, 400);

        hm1.Extent = new(1, 0, 0, 2);
        hm1.FlipRows = false;
        hm1.FlipColumns = false;
        WpfPlot1.Plot.Axes.SetLimits(-1.2, 2.2, -1.2, 3.2);
        WpfPlot1.Plot.Title("Flipped Horizontally (Extent)");
        WpfPlot1.Plot.SavePng("2x3InvertedX1.png", 300, 400);

        hm1.Extent = new(0, 1, 0, 2);
        hm1.FlipRows = false;
        hm1.FlipColumns = true;
        WpfPlot1.Plot.Axes.SetLimits(-1.2, 2.2, -1.2, 3.2);
        WpfPlot1.Plot.Title("Flipped Horizontally (FlipColumns)");
        WpfPlot1.Plot.SavePng("2x3InvertedX2.png", 300, 400);

`

Example output:
2x3 grid Default
2x3InvertedX1
2x3InvertedY2

**Comment by swharden** [comment]
> data-centric ... flipping is no longer referred to as FlipVertically, so this will be a breaking change for some code.

I'm curious, what is the reason for this breaking change? For now I'm going to revert to the original property names. I think flipping horizontally and vertically can be data-centric too, as the default assumption of data[,] is that the first axis is rows (Y) and second axis is columns (X)

If there's a good reason we can go back to FlipRows and FlipColumns. Actually, maybe we can do both? I'll add both now, but I'm open to suggestions along the way!

**Comment by swharden** [comment]
dang, I merged too quick. I'll follow-up with a commit to main in a second that adds a cookbook recipe (and notes in the changelog) about the newly supported `Smooth` property 👍

**Comment by BrianAtZetica** [comment]
> I can already anticipate someone asking about _rotation_ next 

Interesting, as I only recent;y came across this informative Youtube video: https://www.youtube.com/watch?v=1LCEiVDHJmc 

Not likely to have scope to tackle rotation in the short term (and not needed for my project). WIll keep in mind though.

**Comment by BrianAtZetica** [comment]
> I'm curious, what is the reason for this breaking change? For now I'm going to revert to the original property names. I think flipping horizontally and vertically can be data-centric too, as the default assumption of data[,] is that the first axis is rows (Y) and second axis is columns (X)

I guess I was having trouble dealing with inverted axes and vertical/horizontal flips. flipping the data as rows and columns (with out any knowledge of how they will be displayed on the graph) and then deciding how they are presented on the graph with axes limits of flipping made more intuitive sense. 

Glad I flagged, so you could make the descision that best limits inconvenience to yoru user base. 

Thanks

**Pull request merged**
